<?php
/**
 *------
 * BGA framework: © Gregory Isabelli <gisabelli@boardgamearena.com> & Emmanuel Colin <ecolin@boardgamearena.com>
 * mars implementation : © Alena Laskavaia <laskava@gmail.com>
 * 
 * This code has been produced on the BGA studio platform for use on http://boardgamearena.com.
 * See http://en.boardgamearena.com/#!doc/Studio for more information.
 * -----
 *
 * material.inc.php
 *
 * mars game material description
 *
 * Here, you can describe the material of your game with PHP variables.
 *   
 * This file is loaded in your game logic class constructor, ie these variables
 * are available everywhere in your game logic code.
 * 
 * 
 * GENERATED CODE DO NOT EDIT MANAULLY
 *
 */

$this->token_types = [
/* --- gen php begin cards_material --- */
// #project cards, t is color type 1 - green, 2 - blue, 3 - event, 0 - stanard project, 4 - corp, 5 - prelude
 'card_main_1' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 1,
  'name' => clienttranslate("Colonizer Training Camp"),
  't' => 1,
  'cost' => 8,
  'pre' => 'o<=5',
  'tooltip' => clienttranslate("Oxygen must be 5% or less."),
  'vp'=>2,
],
 'card_main_3' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 3,
  'name' => clienttranslate("Deep Well Heating"),
  't' => 1,
  'r' => '1pe,1t',
  'cost' => 13,
  'tooltip' => clienttranslate("Increase your energy production 1 step. Increase temperature 1 step."),
],
 'card_main_4' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 4,
  'name' => clienttranslate("Cloud Seeding"),
  't' => 1,
  'r' => '1npm,2pp,Ref_ph',
  'cost' => 11,
  'pre' => 'w>=3',
  'tooltip' => clienttranslate("Requires 3 ocean tiles. Decrease your MC production 1 step and any heat production 1 step.  Increase your plant production 2 steps."),
],
 'card_main_5' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 5,
  'name' => clienttranslate("Search For Life"),
  't' => 2,
  'r' => 'Ref_m',
  'cost' => 3,
  'pre' => 'o<=6',
  'tooltip' => clienttranslate("Oxygen must be 6% or less. 3 VPs if you have one or more science resource here. Action: Spend 1 MC to reveal and discard the top card of the draw deck. If that card has a microbe tag, add a science resource here."),
],
 'card_main_7' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 7,
  'name' => clienttranslate("Martian Rails"),
  't' => 2,
  'r' => 'Ref_m,Ref_e',
  'cost' => 13,
  'tooltip' => clienttranslate("Action: Spend 1 energy to gain 1 MC for each city tile ON MARS."),
],
 'card_main_8' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 8,
  'name' => clienttranslate("Capital"),
  't' => 1,
  'r' => '5pm,2npe',
  'cost' => 26,
  'pre' => 'w>=4',
  'tooltip' => clienttranslate("Requires 4 ocean tiles. Place [the capital city] tile. Decrease your energy production 2 steps and increase your MC production 5 steps. 1 ADDITIONAL VP FOR EACH OCEAN TILE ADJACENT TO THIS CITY TILE."),
],
 'card_main_9' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 9,
  'name' => clienttranslate("Asteroid"),
  't' => 3,
  'r' => '2u,Ref_p,1t',
  'cost' => 14,
  'tooltip' => clienttranslate("Raise temperature 1 step and gain 2 titanium. Remove up to 3 plants from any player."),
],
 'card_main_10' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 10,
  'name' => clienttranslate("Comet"),
  't' => 3,
  'r' => 'Ref_p,1t,1w',
  'cost' => 21,
  'tooltip' => clienttranslate("Raise temperature 1 step and place an ocean tile. Remove up to 3 plants from any player."),
],
 'card_main_11' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 11,
  'name' => clienttranslate("Big Asteroid"),
  't' => 3,
  'r' => '4u,Ref_p,2t',
  'cost' => 27,
  'tooltip' => clienttranslate("Raise temperature 2 steps and gain 4 titanium. Remove up to 4 plants from any player."),
],
 'card_main_12' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 12,
  'name' => clienttranslate("Water Import From Europa"),
  't' => 2,
  'r' => 'Ref_m,Ref_u,Ref_w',
  'cost' => 25,
  'tooltip' => clienttranslate("1 VP for each Jovian tag you have. Action: Pay 12 MC to place an ocean tile. TITANIUM MAY BE USED as if playing a space card."),
],
 'card_main_15' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 15,
  'name' => clienttranslate("Equatorial Magnetizer"),
  't' => 2,
  'r' => 'Ref_pe,Ref_tr',
  'cost' => 11,
  'tooltip' => clienttranslate("Action: Decrease your energy production 1 step to increase your terraforming rating 1 step."),
],
 'card_main_16' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 16,
  'name' => clienttranslate("Domed Crater"),
  't' => 1,
  'r' => '3pm,1npe,3p',
  'cost' => 24,
  'pre' => 'o<=7',
  'tooltip' => clienttranslate("Oxygen must be 7% or less. Gain 3 plants and place a city tile. Decrease your energy production 1 step and increase MC production 3 steps."),
  'vp'=>1,
],
 'card_main_17' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 17,
  'name' => clienttranslate("Noctis City"),
  't' => 1,
  'r' => '3pm,1npe',
  'cost' => 18,
  'tooltip' => clienttranslate("Decrease your energy production 1 step and increase your MC production 3 steps. Place a tile ON THE RESERVED AREA, disregarding normal placement restrictions."),
],
 'card_main_18' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 18,
  'name' => clienttranslate("Methane From Titan"),
  't' => 1,
  'r' => '2pp,2ph',
  'cost' => 28,
  'pre' => 'o>=2',
  'tooltip' => clienttranslate("Requires 2% oxygen. Increase your heat production 2 steps and your plant production 2 steps."),
  'vp'=>2,
],
 'card_main_19' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 19,
  'name' => clienttranslate("Imported Hydrogen"),
  't' => 3,
  'r' => 'Ref_p,1w',
  'cost' => 16,
  'tooltip' => clienttranslate("Gain 3 plants, or add 3 microbes or 2 animals to ANOTHER card. Place an ocean tile."),
],
 'card_main_20' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 20,
  'name' => clienttranslate("Research Outpost"),
  't' => 2,
  'cost' => 18,
  'tooltip' => clienttranslate("Place a city tile NEXT TO NO OTHER TILE. Effect: When you play a card, you pay 1 MC less for it."),
],
 'card_main_21' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 21,
  'name' => clienttranslate("Phobos Space Haven"),
  't' => 1,
  'r' => '1pu',
  'cost' => 25,
  'tooltip' => clienttranslate("Increase your titanium production 1 step and place a city tile ON THE RESERVED AREA."),
  'vp'=>3,
],
 'card_main_22' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 22,
  'name' => clienttranslate("Black Polar Dust"),
  't' => 1,
  'r' => '2npm,3ph,1w',
  'cost' => 15,
  'tooltip' => clienttranslate("Place an ocean tile. Decrease your MC production 2 steps and increase your heat production 3 steps."),
],
 'card_main_23' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 23,
  'name' => clienttranslate("Arctic Algae"),
  't' => 2,
  'r' => 'Ref_p',
  'cost' => 12,
  'pre' => 't<=-12',
  'tooltip' => clienttranslate("It must be -12°C or colder to play. Gain 1 plant. Effect: When anyone places an ocean tile, gain 2 plants."),
],
 'card_main_24' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 24,
  'name' => clienttranslate("Predators"),
  't' => 2,
  'cost' => 14,
  'pre' => 'o>=11',
  'tooltip' => clienttranslate("Requires 11% oxygen. 1 VP per animal on this card. Action: Remove 1 animal from any card and add it to this card."),
],
 'card_main_26' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 26,
  'name' => clienttranslate("Eos Chasma National Park"),
  't' => 1,
  'r' => '2pm,3p',
  'cost' => 16,
  'pre' => 't>=-12',
  'tooltip' => clienttranslate("Requires -128°C  or warmer. Add 1 animal TO ANY ANIMAL CARD. Gain 3 plants. Increase your MC production 2 steps."),
  'vp'=>1,
],
 'card_main_29' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 29,
  'name' => clienttranslate("Cupola City"),
  't' => 1,
  'r' => '3pm,1npe',
  'cost' => 16,
  'pre' => 'o<=9',
  'tooltip' => clienttranslate("Oxygen must be 9% or less. Place a city tile. Decrease your energy production 1 step and increase your MC production 3 steps."),
],
 'card_main_30' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 30,
  'name' => clienttranslate("Lunar Beam"),
  't' => 1,
  'r' => '2npm,2pe,2ph',
  'cost' => 13,
  'tooltip' => clienttranslate("Decrease your MC production 2 steps and increase your heat production and energy production 2 steps each."),
],
 'card_main_31' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 31,
  'name' => clienttranslate("Optimal Aerobraking"),
  't' => 2,
  'cost' => 7,
  'tooltip' => clienttranslate("Effect: When you place a space event, you gain 3 MC and 3 heat."),
],
 'card_main_32' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 32,
  'name' => clienttranslate("Underground City"),
  't' => 1,
  'r' => '2ps,2npe',
  'cost' => 18,
  'tooltip' => clienttranslate("Place a city tile. Decrease your energy production 2 steps and increase your steel production 2 steps."),
],
 'card_main_33' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 33,
  'name' => clienttranslate("Regolith Eaters"),
  't' => 2,
  'r' => 'Ref_o',
  'cost' => 13,
  'tooltip' => clienttranslate("Action: Add 1 microbe to this card, or remove 2 microbe from this card to raise oxygen level 1 step."),
],
 'card_main_34' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 34,
  'name' => clienttranslate("GHG Producing Bacteria"),
  't' => 2,
  'r' => 'Ref_t',
  'cost' => 8,
  'pre' => 'o>=4',
  'tooltip' => clienttranslate("Requires 4% oxygen. Action: Add 1 microbe to this card, or remove 2 microbes to raise temperature 1 step."),
],
 'card_main_35' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 35,
  'name' => clienttranslate("Ants"),
  't' => 2,
  'cost' => 9,
  'pre' => 'o>=4',
  'tooltip' => clienttranslate("Requires 4% oxygen. 1 VP per 2 microbes on this card. Action: Remove 1 microbe from any card to add 1 to this card."),
],
 'card_main_36' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 36,
  'name' => clienttranslate("Release of Inert Gases"),
  't' => 3,
  'r' => '2tr',
  'cost' => 14,
  'tooltip' => clienttranslate("Raise your terraform rating 2 steps."),
],
 'card_main_37' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 37,
  'name' => clienttranslate("Nitrogen-Rich Asteroid"),
  't' => 3,
  'r' => 'Ref_pp,2tr,1t',
  'cost' => 31,
  'tooltip' => clienttranslate("Raise your terraforming rating 2 steps and temperature 1 step. Increase your plant production 1 step, or 4 steps if you have 3 plant tags."),
],
 'card_main_38' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 38,
  'name' => clienttranslate("Rover Construction"),
  't' => 2,
  'r' => 'Ref_m',
  'cost' => 8,
  'tooltip' => clienttranslate("Effect: When any city tile is placed, gain 2 MC"),
  'vp'=>1,
],
 'card_main_39' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 39,
  'name' => clienttranslate("Deimos Down"),
  't' => 3,
  'r' => '4s,Ref_p,3t',
  'cost' => 31,
  'tooltip' => clienttranslate("Raise temperature 3 steps and gain 4 steel. Remove up to 8 plants from any player."),
],
 'card_main_40' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 40,
  'name' => clienttranslate("Asteroid Mining"),
  't' => 1,
  'r' => '2pu',
  'cost' => 30,
  'tooltip' => clienttranslate("Increase your titanium production 2 steps."),
  'vp'=>2,
],
 'card_main_41' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 41,
  'name' => clienttranslate("Food Factory"),
  't' => 1,
  'r' => '4pm,1npp',
  'cost' => 12,
  'tooltip' => clienttranslate("Decrease your plant production 1 step and increase your MC production 4 steps."),
  'vp'=>1,
],
 'card_main_42' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 42,
  'name' => clienttranslate("Archaebacteria"),
  't' => 1,
  'r' => '1pp',
  'cost' => 6,
  'pre' => 't<=-18',
  'tooltip' => clienttranslate("It must be -18°C or colder. Increase your plant production 1 step."),
],
 'card_main_43' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 43,
  'name' => clienttranslate("Carbonate Processing"),
  't' => 1,
  'r' => '1npe,3ph',
  'cost' => 6,
  'tooltip' => clienttranslate("Decrease your energy production 1 step and increase your heat production 3 steps."),
],
 'card_main_44' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 44,
  'name' => clienttranslate("Natural Preserve"),
  't' => 1,
  'r' => '1pm',
  'cost' => 9,
  'pre' => 'o<=4',
  'tooltip' => clienttranslate("Oxygen must be 4% or less. Place this tile NEXT TO NO OTHER TILE. Increase your MC production 1 step."),
  'vp'=>1,
],
 'card_main_45' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 45,
  'name' => clienttranslate("Nuclear Power"),
  't' => 1,
  'r' => '2npm,3pe',
  'cost' => 10,
  'tooltip' => clienttranslate("Decrease your MC production 2 steps and increase your energy production 3 steps."),
],
 'card_main_47' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 47,
  'name' => clienttranslate("Algae"),
  't' => 1,
  'r' => '2pp,1p',
  'cost' => 10,
  'pre' => 'w>=5',
  'tooltip' => clienttranslate("Requires 5 ocean tiles. Gain 1 plant and increase your plant production 2 steps."),
],
 'card_main_48' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 48,
  'name' => clienttranslate("Adapted Lichen"),
  't' => 1,
  'r' => '1pp',
  'cost' => 9,
  'tooltip' => clienttranslate("Increase your plant production 1 step."),
],
 'card_main_52' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 52,
  'name' => clienttranslate("Fish"),
  't' => 2,
  'r' => 'Ref_pp',
  'cost' => 9,
  'pre' => 't>=2',
  'tooltip' => clienttranslate("Requires 2°C or warmer. Decrease any plant production 1 step. 1 VP for each animal on this card. Action: Add 1 animal to this card."),
],
 'card_main_53' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 53,
  'name' => clienttranslate("Lake Marineris"),
  't' => 1,
  'r' => '2w',
  'cost' => 18,
  'pre' => 't>=0',
  'tooltip' => clienttranslate("Requires 0°C or warmer. Place 2 ocean tiles."),
  'vp'=>2,
],
 'card_main_54' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 54,
  'name' => clienttranslate("Small Animals"),
  't' => 2,
  'r' => 'Ref_pp',
  'cost' => 6,
  'pre' => 'o>=6',
  'tooltip' => clienttranslate("Requires 6% oxygen. Decrease any plant production 1 step. 1 VP per 2 animals on this card. Action: Add 1 animal to this card."),
],
 'card_main_55' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 55,
  'name' => clienttranslate("Kelp Farming"),
  't' => 1,
  'r' => '2pm,3pp,2p',
  'cost' => 17,
  'pre' => 'w>=6',
  'tooltip' => clienttranslate("Requires 6 ocean tiles. Increase your MC production 2 steps and your plant production 3 steps. Gain 2 plants."),
  'vp'=>1,
],
 'card_main_58' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 58,
  'name' => clienttranslate("Beam From a Thorium Asteroid"),
  't' => 1,
  'r' => '3pe,3ph',
  'cost' => 32,
  'tooltip' => clienttranslate("Requires a Jovian tag. Increase your heat production and energy production 3 steps each."),
  'vp'=>1,
],
 'card_main_59' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 59,
  'name' => clienttranslate("Mangrove"),
  't' => 1,
  'r' => '1o',
  'cost' => 12,
  'pre' => 't>=4',
  'tooltip' => clienttranslate("Requires +4°C or warmer. Place a Greenery tile ON AN AREA RESERVED FOR OCEAN and raise oxygen 1 step. Disregard normal placement restrictions for this."),
  'vp'=>1,
],
 'card_main_60' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 60,
  'name' => clienttranslate("Trees"),
  't' => 1,
  'r' => '3pp,1p',
  'cost' => 13,
  'pre' => 't>=-4',
  'tooltip' => clienttranslate("Requires -4°C or warmer. Increase your plant production 3 steps. Gain 1 plant."),
  'vp'=>1,
],
 'card_main_63' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 63,
  'name' => clienttranslate("Mining Expedition"),
  't' => 3,
  'r' => '2s,Ref_p,1o',
  'cost' => 12,
  'tooltip' => clienttranslate("Raise oxygen 1 step. Remove 2 plants from any player. Gain 2 steel."),
],
 'card_main_67' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 67,
  'name' => clienttranslate("Mining Rights"),
  't' => 1,
  'r' => 'Ref_ps,Ref_pu',
  'cost' => 9,
  'tooltip' => clienttranslate("Place [the mining] tile on an area with a steel or titanium placement bonus. Increase that production 1 step."),
],
 'card_main_72' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 72,
  'name' => clienttranslate("Birds"),
  't' => 2,
  'r' => 'Ref_pp',
  'cost' => 10,
  'pre' => 'o>=13',
  'tooltip' => clienttranslate("Requires 13% oxygen. Decrease any plant production 2 steps. 1 VP for each animal on this card Action: Add an animal to this card."),
],
 'card_main_75' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 75,
  'name' => clienttranslate("Towing a Comet"),
  't' => 3,
  'r' => '2p,1o,1w',
  'cost' => 23,
  'tooltip' => clienttranslate("Gain 2 plants. Raise oxygen level 1 step and place an ocean tile."),
],
 'card_main_76' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 76,
  'name' => clienttranslate("Space Mirrors"),
  't' => 2,
  'r' => 'Ref_pe,Ref_m',
  'cost' => 3,
  'tooltip' => clienttranslate("Action: Spend 7MC to increase your energy production 1 step."),
],
 'card_main_77' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 77,
  'name' => clienttranslate("Solar Wind Power"),
  't' => 1,
  'r' => '1pe,2u',
  'cost' => 11,
  'tooltip' => clienttranslate("Increase your energy production 1 step and gain 2 titanium."),
],
 'card_main_78' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 78,
  'name' => clienttranslate("Ice Asteroid"),
  't' => 3,
  'r' => '2w',
  'cost' => 23,
  'tooltip' => clienttranslate("Place 2 ocean tiles."),
],
 'card_main_80' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 80,
  'name' => clienttranslate("Giant Ice Asteroid"),
  't' => 3,
  'r' => 'Ref_p,2t,2w',
  'cost' => 36,
  'tooltip' => clienttranslate("Raise temperature 2 steps and place 2 ocean tiles. Remove up to 6 plants from any plyer."),
],
 'card_main_81' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 81,
  'name' => clienttranslate("Ganymede Colony"),
  't' => 1,
  'cost' => 20,
  'tooltip' => clienttranslate("Place a city tile ON THE RESERVED AREA [for Ganymede Colony]. 1 VP per Jovian tag you have."),
],
 'card_main_83' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 83,
  'name' => clienttranslate("Giant Space Mirror"),
  't' => 1,
  'r' => '3pe',
  'cost' => 17,
  'tooltip' => clienttranslate("Increase your energy production 3 steps."),
],
 'card_main_87' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 87,
  'name' => clienttranslate("Grass"),
  't' => 1,
  'r' => '1pp,3p',
  'cost' => 11,
  'pre' => 't>=-16',
  'tooltip' => clienttranslate("Requires -16°C or warmer. Increase your plant production 1 step. Gain 3 plants."),
],
 'card_main_88' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 88,
  'name' => clienttranslate("Heather"),
  't' => 1,
  'r' => '1pp,1p',
  'cost' => 6,
  'pre' => 't>=-14',
  'tooltip' => clienttranslate("Requires -14°C or warmer. Increase your plant production 1 step. Gain 1 plant."),
],
 'card_main_89' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 89,
  'name' => clienttranslate("Peroxide Power"),
  't' => 1,
  'r' => '1npm,2pe',
  'cost' => 7,
  'tooltip' => clienttranslate("Decrease your MC production 1 step and increase your energy production 2 steps."),
],
 'card_main_93' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 93,
  'name' => clienttranslate("Bushes"),
  't' => 1,
  'r' => '2pp,2p',
  'cost' => 10,
  'pre' => 't>=-10',
  'tooltip' => clienttranslate("Requires -10°C or warmer. Increase your plant production 2 steps. Gain 2 plants."),
],
 'card_main_96' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 96,
  'name' => clienttranslate("Greenhouses"),
  't' => 1,
  'r' => 'Ref_p',
  'cost' => 6,
  'tooltip' => clienttranslate("Gain 1 plant for each city tile in play."),
],
 'card_main_97' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 97,
  'name' => clienttranslate("Nuclear Zone"),
  't' => 1,
  'r' => '2t',
  'cost' => 10,
  'tooltip' => clienttranslate("Place [the nuclear zone] tile and raise the temperature 2 steps."),
  'vp'=>-2,
],
 'card_main_100' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 100,
  'name' => clienttranslate("Fueled Generators"),
  't' => 1,
  'r' => '1npm,1pe',
  'cost' => 1,
  'tooltip' => clienttranslate("Decrease your MC production 1 step and increase your energy production 1 step."),
],
 'card_main_101' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 101,
  'name' => clienttranslate("Ironworks"),
  't' => 2,
  'r' => 'Ref_s,Ref_e,Ref_o',
  'cost' => 11,
  'tooltip' => clienttranslate("Action: Spend 4 energy to gain 1 steel and increase oxygen 1 step."),
],
 'card_main_102' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 102,
  'name' => clienttranslate("Power Grid"),
  't' => 1,
  'r' => 'Ref_pe',
  'cost' => 18,
  'tooltip' => clienttranslate("Increase your energy production 1 step for each power tag you have, including this.)"),
],
 'card_main_103' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 103,
  'name' => clienttranslate("Steelworks"),
  't' => 2,
  'r' => 'Ref_s,Ref_e,Ref_o',
  'cost' => 15,
  'tooltip' => clienttranslate("Action: Spend 4 energy to gain 2 steel and increase oxygen 1 step."),
],
 'card_main_104' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 104,
  'name' => clienttranslate("Ore Processor"),
  't' => 2,
  'r' => 'Ref_u,Ref_p,Ref_o',
  'cost' => 13,
  'tooltip' => clienttranslate("Action: Spend 4 energy to gain 1 titanium and increase oxygen 1 step."),
],
 'card_main_108' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 108,
  'name' => clienttranslate("Open City"),
  't' => 1,
  'r' => '4pm,1npe,2p',
  'cost' => 23,
  'pre' => 'o>=12',
  'tooltip' => clienttranslate("Requires 12% oxygen. Decrease your energy production 1 step and increase your MC production 4 steps. Gain 2 plants and place a city tile."),
  'vp'=>1,
],
 'card_main_113' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 113,
  'name' => clienttranslate("Solar Power"),
  't' => 1,
  'r' => '1pe',
  'cost' => 11,
  'tooltip' => clienttranslate("Increase your energy production 1 step."),
  'vp'=>1,
],
 'card_main_114' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 114,
  'name' => clienttranslate("Breathing Filters"),
  't' => 1,
  'cost' => 11,
  'pre' => 'o>=7',
  'tooltip' => clienttranslate("Requires 7% oxygen."),
  'vp'=>2,
],
 'card_main_115' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 115,
  'name' => clienttranslate("Artificial Photosynthesis"),
  't' => 1,
  'r' => 'Ref_pp,Ref_pe',
  'cost' => 12,
  'tooltip' => clienttranslate("Increase your plant production 1 step or your energy production 2 steps."),
],
 'card_main_116' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 116,
  'name' => clienttranslate("Artificial Lake"),
  't' => 1,
  'r' => '1w',
  'cost' => 15,
  'pre' => 't>=-6',
  'tooltip' => clienttranslate("Requires -6°C or warmer. Place 1 ocean tile ON AN AREA NOT RESERVED FOR OCEAN."),
  'vp'=>1,
],
 'card_main_117' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 117,
  'name' => clienttranslate("Geothermal Power"),
  't' => 1,
  'r' => '2pe',
  'cost' => 11,
  'tooltip' => clienttranslate("Increase your energy production 2 steps."),
],
 'card_main_118' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 118,
  'name' => clienttranslate("Farming"),
  't' => 1,
  'r' => '2pm,2pp,2p',
  'cost' => 16,
  'pre' => 't>=4',
  'tooltip' => clienttranslate("Requires +4°C or warmer. Increase your MC production 2 steps and your plant production 2 steps. Gain 2 plants."),
  'vp'=>2,
],
 'card_main_119' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 119,
  'name' => clienttranslate("Dust Seals"),
  't' => 1,
  'cost' => 2,
  'pre' => 'w<=3',
  'tooltip' => clienttranslate("Requires 3 or less ocean tiles."),
  'vp'=>1,
],
 'card_main_120' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 120,
  'name' => clienttranslate("Urbanized Area"),
  't' => 1,
  'r' => '2pm,1npe',
  'cost' => 10,
  'tooltip' => clienttranslate("Decrease your energy production 1 step and increase your MC production 2 steps. Place a city tile ADJACENT TO AT LEAST 2 OTHER CITY TILES."),
],
 'card_main_122' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 122,
  'name' => clienttranslate("Moss"),
  't' => 1,
  'r' => '1pp,1np',
  'cost' => 4,
  'pre' => 'w>=3',
  'tooltip' => clienttranslate("Requires 3 ocean tiles and that you lose 1 plant. Increase your plant production 1 step."),
],
 'card_main_126' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 126,
  'name' => clienttranslate("GHG Factories"),
  't' => 1,
  'r' => '1npe,4ph',
  'cost' => 11,
  'tooltip' => clienttranslate("Decrease your energy production 1 step and increase your heat production 4 steps."),
],
 'card_main_127' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 127,
  'name' => clienttranslate("Subterranean Reservoir"),
  't' => 3,
  'r' => '1w',
  'cost' => 11,
  'tooltip' => clienttranslate("Place 1 ocean tile."),
],
 'card_main_128' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 128,
  'name' => clienttranslate("Ecological Zone"),
  't' => 2,
  'cost' => 12,
  'tooltip' => clienttranslate("Requires that you have a greenery tile. Place [the Ecological Zone] tile ADJACENT TO ANY GREENERY TILE. 1 VP per 2 animals on this card. Effect: When you play an animal or a plant tag (including these 2), add an animal to this card."),
],
 'card_main_129' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 129,
  'name' => clienttranslate("Zeppelins"),
  't' => 1,
  'r' => 'Ref_pm',
  'cost' => 13,
  'pre' => 'o>=5',
  'tooltip' => clienttranslate("Requires 5% oxygen. Increase your MC production 1 step for each city tile ON MARS."),
  'vp'=>1,
],
 'card_main_130' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 130,
  'name' => clienttranslate("Worms"),
  't' => 1,
  'r' => 'Ref_pp',
  'cost' => 8,
  'pre' => 'o>=4',
  'tooltip' => clienttranslate("Requires 4% oxygen. Increase your plant production 1 step for every 2 microbe tags you have, including this."),
],
 'card_main_131' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 131,
  'name' => clienttranslate("Decomposers"),
  't' => 2,
  'cost' => 5,
  'pre' => 'o>=3',
  'tooltip' => clienttranslate("Requires 3# oxygen. 1 VP per 3 microbes on this card. Effect: When you play an animal, plant, or microbe tag, including this, add a microbe to this card."),
],
 'card_main_132' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 132,
  'name' => clienttranslate("Fusion Power"),
  't' => 1,
  'r' => '3pe',
  'cost' => 14,
  'tooltip' => clienttranslate("Requires 2 power tags. Increase your energy production 3 steps."),
],
 'card_main_133' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 133,
  'name' => clienttranslate("Symbiotic Fungus"),
  't' => 2,
  'cost' => 4,
  'pre' => 't>=-14',
  'tooltip' => clienttranslate("Requires -14°C or warmer. Action: Add a microbe to ANOTHER card."),
],
 'card_main_134' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 134,
  'name' => clienttranslate("Extreme-Cold Fungus"),
  't' => 2,
  'r' => 'Ref_p',
  'cost' => 13,
  'pre' => 't<=-10',
  'tooltip' => clienttranslate("It must be -10°C or colder. Action: Gain 1 plant or add 2 microbes to ANOTHER card."),
],
 'card_main_135' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 135,
  'name' => clienttranslate("Advanced Ecosystems"),
  't' => 1,
  'cost' => 11,
  'tooltip' => clienttranslate("Requires a plant tag, a microbe tag, and an animal tag."),
  'vp'=>3,
],
 'card_main_136' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 136,
  'name' => clienttranslate("Great Dam"),
  't' => 1,
  'r' => '2pe',
  'cost' => 12,
  'pre' => 'w>=4',
  'tooltip' => clienttranslate("Requires 4 ocean tiles. Increase your energy production 2 steps."),
  'vp'=>1,
],
 'card_main_138' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 138,
  'name' => clienttranslate("Strip Mine"),
  't' => 1,
  'r' => '2ps,1pu,2npe,2o',
  'cost' => 25,
  'tooltip' => clienttranslate("Decrease your energy production 2 steps. Increase your steel production 2 steps and your titanium production 1 step. Raise oxygen 2 steps."),
],
 'card_main_139' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 139,
  'name' => clienttranslate("Wave Power"),
  't' => 1,
  'r' => '1pe',
  'cost' => 8,
  'pre' => 'w>=3',
  'tooltip' => clienttranslate("Requires 3 ocean tiles. Increase your energy production 1 step."),
  'vp'=>1,
],
 'card_main_140' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 140,
  'name' => clienttranslate("Lava Flows"),
  't' => 3,
  'r' => '2t',
  'cost' => 18,
  'tooltip' => clienttranslate("Raise the temperature 2 steps and place this [the Lava Flow] tile ON EITHER THARSIS THOLUS, ASCRAEUS MONS, PAVONIS MONS OR ARSIA MONS."),
],
 'card_main_141' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 141,
  'name' => clienttranslate("Power Plant"),
  't' => 1,
  'r' => '1pe',
  'cost' => 4,
  'tooltip' => clienttranslate("Increase your energy production 1 step."),
],
 'card_main_142' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 142,
  'name' => clienttranslate("Mohole Area"),
  't' => 1,
  'r' => '4ph',
  'cost' => 20,
  'tooltip' => clienttranslate("Increase your heat production 4 steps. Place [the Mohole Area] tile ON AN AREA RESERVED FOR OCEAN."),
],
 'card_main_143' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 143,
  'name' => clienttranslate("Large Convoy"),
  't' => 3,
  'r' => 'Ref_p,1w',
  'cost' => 36,
  'tooltip' => clienttranslate("Place an ocean tile and draw 2 cards. Gain 5 plants, or add 4 animals to ANOTHER card."),
  'vp'=>2,
],
 'card_main_145' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 145,
  'name' => clienttranslate("Tectonic Stress Power"),
  't' => 1,
  'r' => '3pe',
  'cost' => 18,
  'tooltip' => clienttranslate("Requires 2 science tags. Increase your energy production 3 steps."),
  'vp'=>1,
],
 'card_main_146' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 146,
  'name' => clienttranslate("Nitrophilic Moss"),
  't' => 1,
  'r' => '2pp,2np',
  'cost' => 8,
  'pre' => 'w>=3',
  'tooltip' => clienttranslate("Requires 3 ocean tiles and that you lose 2 plants. Increase your plant production 2 steps."),
],
 'card_main_147' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 147,
  'name' => clienttranslate("Herbivores"),
  't' => 2,
  'r' => 'Ref_pp',
  'cost' => 12,
  'pre' => 'o>=8',
  'tooltip' => clienttranslate("Requires 8% oxygen. Add 1 animal to this card. Decrease any plant production 1 step. 1 VP per 2 animals on this card. Effect: When you place a greenery tile, add an animal to this card."),
],
 'card_main_148' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 148,
  'name' => clienttranslate("Insects"),
  't' => 1,
  'r' => 'Ref_pp',
  'cost' => 9,
  'pre' => 'o>=6',
  'tooltip' => clienttranslate("Requires 6% oxygen. Increase your plant production 1 step for each plant tag you have."),
],
 'card_main_152' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 152,
  'name' => clienttranslate("Insulation"),
  't' => 1,
  'r' => 'Ref_pm,Ref_ph',
  'cost' => 2,
  'tooltip' => clienttranslate("Decrease your heat production any number of steps and increase your MC production the same number of steps."),
],
 'card_main_153' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 153,
  'name' => clienttranslate("Adaptation Technology"),
  't' => 2,
  'cost' => 12,
  'tooltip' => clienttranslate("Effect: Your global requirements are +2 or -2 steps, your choice in each case."),
  'vp'=>1,
],
 'card_main_155' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 155,
  'name' => clienttranslate("Designed Microorganisms"),
  't' => 1,
  'r' => '2pp',
  'cost' => 16,
  'pre' => 't<=-14',
  'tooltip' => clienttranslate("It must be -14°C or colder. Increase your plant production 2 steps."),
],
 'card_main_157' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 157,
  'name' => clienttranslate("Nitrite Reducing Bacteria"),
  't' => 2,
  'r' => 'Ref_tr',
  'cost' => 11,
  'tooltip' => clienttranslate("Add 3 microbes to this card. Action: Add 1 microbe to this card, or remove 3 microbes to increase your TR 1 step."),
],
 'card_main_158' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 158,
  'name' => clienttranslate("Industrial Microbes"),
  't' => 1,
  'r' => '1ps,1pe',
  'cost' => 12,
  'tooltip' => clienttranslate("Increase your energy production and your steel production 1 step each."),
],
 'card_main_159' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 159,
  'name' => clienttranslate("Lichen"),
  't' => 1,
  'r' => '1pp',
  'cost' => 7,
  'pre' => 't>=-24',
  'tooltip' => clienttranslate("Requires -24°C or warmer. Increase your plant production 1 step."),
],
 'card_main_161' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 161,
  'name' => clienttranslate("Convoy From Europa"),
  't' => 3,
  'r' => '1w',
  'cost' => 15,
  'tooltip' => clienttranslate("Place 1 ocean tile and draw 1 card."),
],
 'card_main_162' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 162,
  'name' => clienttranslate("Imported GHG"),
  't' => 3,
  'r' => '1ph,3h',
  'cost' => 7,
  'tooltip' => clienttranslate("Increase your heat production 1 step and gain 3 hear."),
],
 'card_main_163' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 163,
  'name' => clienttranslate("Imported Nitrogen"),
  't' => 3,
  'r' => '4p,1tr',
  'cost' => 23,
  'tooltip' => clienttranslate("Raise your TR 1 step and gain 4 plants. Add 3 microbes to ANOTHER card and 2 animals to ANOTHER card."),
],
 'card_main_164' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 164,
  'name' => clienttranslate("Micro-Mills"),
  't' => 1,
  'r' => '1ph',
  'cost' => 3,
  'tooltip' => clienttranslate("Increase your heat production 1 step."),
],
 'card_main_165' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 165,
  'name' => clienttranslate("Magnetic Field Generators"),
  't' => 1,
  'r' => '2pp,4npe,3tr',
  'cost' => 20,
  'tooltip' => clienttranslate("Decrease your energy production 4 steps and increase your plant production 2 steps. Raise your TR 3 steps."),
],
 'card_main_166' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 166,
  'name' => clienttranslate("Shuttles"),
  't' => 2,
  'r' => '2pm,1npe',
  'cost' => 10,
  'pre' => 'o>=5',
  'tooltip' => clienttranslate("Requires 5% oxygen. Decrease your energy production 1 step and increase your MC production 2 steps. Effect: When you play a space card, you pay 2MC less for it."),
  'vp'=>1,
],
 'card_main_167' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 167,
  'name' => clienttranslate("Import of Advanced GHG"),
  't' => 3,
  'r' => '2ph',
  'cost' => 9,
  'tooltip' => clienttranslate("Increase your heat production 2 steps."),
],
 'card_main_168' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 168,
  'name' => clienttranslate("Windmills"),
  't' => 1,
  'r' => '1pe',
  'cost' => 6,
  'pre' => 'o>=7',
  'tooltip' => clienttranslate("Requires 7% oxygen. Increase your energy production 1 step."),
  'vp'=>1,
],
 'card_main_169' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 169,
  'name' => clienttranslate("Tundra Farming"),
  't' => 1,
  'r' => '2pm,1pp,1p',
  'cost' => 16,
  'pre' => 't>=-6',
  'tooltip' => clienttranslate("Requires -6°C or warmer. Increase your plant production 1 step and your MC production 2 steps. Gain 1 plant."),
  'vp'=>2,
],
 'card_main_170' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 170,
  'name' => clienttranslate("Aerobraked Ammonia Asteroid"),
  't' => 3,
  'r' => '1pp,3ph',
  'cost' => 26,
  'tooltip' => clienttranslate("Add 2 microbes to ANOTHER card. Increase your heat production 3 steps and your plant production 1 step."),
],
 'card_main_171' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 171,
  'name' => clienttranslate("Magnetic Field Dome"),
  't' => 1,
  'r' => '1pp,2npe,1tr',
  'cost' => 5,
  'tooltip' => clienttranslate("Decrease your energy production 2 steps and increase your plant production 1 step. Raise your terraform rating 1 step."),
],
 'card_main_172' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 172,
  'name' => clienttranslate("Pets"),
  't' => 2,
  'cost' => 10,
  'tooltip' => clienttranslate("Add 1 animal to this card. 1 VP per 2 animals here. Effect: When any city tile is placed, add an animal to this card.  Animals may not be removed from this card."),
],
 'card_main_174' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 174,
  'name' => clienttranslate("Protected Valley"),
  't' => 1,
  'r' => '2pm,1o',
  'cost' => 23,
  'tooltip' => clienttranslate("Increase your MC production 2 steps. Place a greenery tile ON AN AREA RESERVED FOR OCEAN, disregarding normal placement restrictions, and increase oxygen 1 step."),
],
 'card_main_176' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 176,
  'name' => clienttranslate("Noctis Farming"),
  't' => 1,
  'r' => '1pm,2p',
  'cost' => 10,
  'pre' => 't>=-20',
  'tooltip' => clienttranslate("Requires -20°C or warmer. Increase your MC production 1 step and gain 2 plants."),
  'vp'=>1,
],
 'card_main_177' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 177,
  'name' => clienttranslate("Water Splitting Plant"),
  't' => 2,
  'r' => 'Ref_e,Ref_o',
  'cost' => 12,
  'pre' => 'w>=2',
  'tooltip' => clienttranslate("Requires 2 ocean tiles. Action: Spend 3 energy to raise oxygen 1 step."),
],
 'card_main_178' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 178,
  'name' => clienttranslate("Heat Trappers"),
  't' => 1,
  'r' => '1pe,Ref_h',
  'cost' => 6,
  'tooltip' => clienttranslate("Decrease any heat production 2 steps and increase your energy production 1 step."),
  'vp'=>-1,
],
 'card_main_179' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 179,
  'name' => clienttranslate("Soil Factory"),
  't' => 1,
  'r' => '1pp,1npe',
  'cost' => 9,
  'tooltip' => clienttranslate("Decrease your energy production 1 step and increase your plant production 1 step."),
  'vp'=>1,
],
 'card_main_181' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 181,
  'name' => clienttranslate("Ice cap Melting"),
  't' => 3,
  'r' => '1w',
  'cost' => 5,
  'pre' => 't>=2',
  'tooltip' => clienttranslate("Requires +2°C or warmer. Place 1 ocean tile."),
],
 'card_main_183' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 183,
  'name' => clienttranslate("Biomass Combustors"),
  't' => 1,
  'r' => 'Ref_pp,2pe',
  'cost' => 4,
  'pre' => 'o>=6',
  'tooltip' => clienttranslate("Requires 6% oxygen. Decrease any plant production 1 step and increase your energy production 2 steps."),
  'vp'=>-1,
],
 'card_main_184' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 184,
  'name' => clienttranslate("Livestock"),
  't' => 2,
  'r' => '2pm,1npp',
  'cost' => 13,
  'pre' => 'o>=9',
  'tooltip' => clienttranslate("Requires 9% oxygen. Decrease your plant production 1 step and increase your MC production 2 steps. 1 VP for each animal on this card. Action: Add 1 animal to this card."),
],
 'card_main_187' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 187,
  'name' => clienttranslate("Aquifer Pumping"),
  't' => 2,
  'r' => 'Ref_m,Ref_s,Ref_w',
  'cost' => 18,
  'tooltip' => clienttranslate("Action: Spend 8 MC to place 1 ocean tile. STEEL MAY BE USED as if you were playing a building card."),
],
 'card_main_188' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 188,
  'name' => clienttranslate("Flooding"),
  't' => 3,
  'r' => 'Ref_m,1w',
  'cost' => 7,
  'tooltip' => clienttranslate("Place an ocean tile. IF THERE ARE TILES ADJACENT TO THIS OCEAN TILE, YOU MAY REMOVE 4 MC FROM THE OWNER OF ONE OF THOSE TILES."),
  'vp'=>-1,
],
 'card_main_189' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 189,
  'name' => clienttranslate("Energy Saving"),
  't' => 1,
  'r' => 'Ref_pe',
  'cost' => 15,
  'tooltip' => clienttranslate("Increase your energy production 1 step for each city tile in play."),
],
 'card_main_190' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 190,
  'name' => clienttranslate("Local Heat Trapping"),
  't' => 3,
  'r' => 'Ref_p,5nh',
  'cost' => 1,
  'tooltip' => clienttranslate("Spend 5 heat to either gain 4 plants, or to add 2 animals to ANOTHER card."),
],
 'card_main_191' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 191,
  'name' => clienttranslate("Permafrost extraction"),
  't' => 3,
  'cost' => 8,
  'pre' => 't>=-8',
  'tooltip' => clienttranslate("Requires -8°C or warmer. Place 1 ocean tile."),
],
 'card_main_193' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 193,
  'name' => clienttranslate("Plantation"),
  't' => 1,
  'r' => '1o',
  'cost' => 15,
  'tooltip' => clienttranslate("Requires 2 science tags. Place a greenery tile and raise oxygen 1 step."),
],
 'card_main_198' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 198,
  'name' => clienttranslate("Immigration Shuttles"),
  't' => 1,
  'r' => '5pm',
  'cost' => 31,
  'tooltip' => clienttranslate("Increase your MC production 5 steps. 1 VP for every 3rd city in play."),
],
 'card_main_200' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 200,
  'name' => clienttranslate("Immigrant City"),
  't' => 2,
  'r' => 'Ref_pm,1npe',
  'cost' => 13,
  'tooltip' => clienttranslate("Decrease your energy production 1 step and decrease your MC production 2 steps. Place a city tile. Effect: Each time a city tile is placed, including this, increase your MC production 1 step."),
],
 'card_main_202' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 202,
  'name' => clienttranslate("Underground Detonations"),
  't' => 2,
  'r' => 'Ref_ph,Ref_m',
  'cost' => 6,
  'tooltip' => clienttranslate("Action: Spend 10 MC to increase your heat production 2 steps."),
],
 'card_main_203' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 203,
  'name' => clienttranslate("Soletta"),
  't' => 1,
  'r' => '7ph',
  'cost' => 35,
  'tooltip' => clienttranslate("Increase your heat production 7 steps."),
],
 'card_main_205' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 205,
  'name' => clienttranslate("Rad-Chem Factory"),
  't' => 1,
  'r' => '1npe,2tr',
  'cost' => 8,
  'tooltip' => clienttranslate("Decrease your energy production 1 step. Raise your terraform rating 2 steps."),
],
 'card_main_206' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 206,
  'name' => clienttranslate("Special Design"),
  't' => 3,
  'cost' => 4,
  'tooltip' => clienttranslate("The next card you play this generation is +2 or -2 in global requirements, your choice."),
],
/* --- gen php end cards_material --- */
/* --- gen php begin proj_material --- */
// #corp cards
// #
 'card_corp_1' => [  //
  'location' => 'deck_corp',
  'num' => 1,
  'name' => clienttranslate("Begginer Corp"),
  't' => 4,
  'r' => '42m',
  'cost' => 10,
  'pre' => 'This is a begginer corp',
],
// #
// #standard projects
// #
 'card_stanproj_1' => [  //
  'location' => 'display_main',
  'count' => 1,
  'create' => 1,
  'num' => 1,
  'name' => clienttranslate("Sell patents"),
  't' => 0,
  'r' => '[1,](sell)',
  'cost' => 0,
  'tooltip' => clienttranslate("Discard X card to gain X MC"),
],
 'card_stanproj_2' => [  //
  'location' => 'display_main',
  'count' => 1,
  'create' => 1,
  'num' => 2,
  'name' => clienttranslate("Draw card"),
  't' => 0,
  'r' => 'draw',
  'cost' => 4,
  'tooltip' => clienttranslate("Pay 4 ME draw card"),
],
 'card_stanproj_4' => [  //
  'location' => 'display_main',
  'count' => 1,
  'create' => 1,
  'num' => 4,
  'name' => clienttranslate("Aquifer"),
  't' => 0,
  'r' => 'w',
  'cost' => 18,
  'tooltip' => clienttranslate("For 18 M€ you get to place an ocean tile (you also get 1 TR and collect any placement bonus for the tile)"),
],
 'card_stanproj_5' => [  //
  'location' => 'display_main',
  'count' => 1,
  'create' => 1,
  'num' => 5,
  'name' => clienttranslate("Greenery"),
  't' => 0,
  'r' => 'o',
  'cost' => 23,
  'tooltip' => clienttranslate("For 23 M€ you get to place a greenery tile, which increases oxygen level (and your TR) 1 step, and collect any placement bonus for the tile. Put a player marker on the tile"),
],
/* --- gen php end proj_material --- */
/* --- gen php begin loc_material --- */
 'deck_main' => [  //
  'type' => 'location',
  'name' => clienttranslate("Main Deck"),
  'location' => 'main_area',
  'scope' => 'global',
  'counter' => 'public',
  'content' => 'hidden',
  'auto_resuffle'=>'discard_main',
],
 'deck_corp' => [  //
  'type' => 'location',
  'name' => clienttranslate("Corp Deck"),
  'location' => 'limbo',
  'scope' => 'global',
  'counter' => 'hidden',
  'content' => 'hidden',
],
 'discard_main' => [  //
  'type' => 'location',
  'name' => clienttranslate("Main Discard"),
  'location' => 'main_area',
  'scope' => 'global',
  'counter' => 'public',
  'content' => 'public',
],
 'hand' => [  //
  'type' => 'location',
  'name' => clienttranslate("Hand"),
  'location' => 'hand_area',
  'scope' => 'player',
  'counter' => 'public',
  'content' => 'private',
],
 'tableau' => [  //
  'type' => 'location',
  'name' => clienttranslate("Player Area"),
  'location' => 'tableau_area',
  'scope' => 'player',
  'counter' => 'public',
  'content' => 'public',
],
 'display_main' => [  //
  'type' => 'location',
  'name' => clienttranslate("Display"),
  'location' => 'main_area',
  'scope' => 'global',
  'counter' => 'public',
  'content' => 'public',
],
 'limbo' => [  //
  'type' => 'location',
  'name' => clienttranslate("Limbo"),
  'scope' => 'global',
  'counter' => 'hidden',
  'content' => 'hidden',
],
/* --- gen php end loc_material --- */

/* --- gen php begin op_material --- */
 'op_card' => [  //
  'undo' => 'true',
  'type' => 'card',
  'name' => clienttranslate("Play Card"),
  'params' => 'target,payment',
  'prompt' => '${you} must select a card to play',
],
 'op_stan' => [  //
  'undo' => 'true',
  'type' => 'stan',
  'name' => clienttranslate("Standard Project"),
  'params' => 'target,payment',
  'prompt' => '${you} must select a basic project to play',
],
// #x|Place Tile|target|${you} must select a location to place tile
 'op_w' => [  //
  'undo' => 'true',
  'type' => 'w',
  'name' => clienttranslate("Place Ocean Tile"),
  'prompt' => '${you} must select a location to place an ocean tile',
],
 'op_discard' => [  //
  'undo' => 'true',
  'type' => 'discard',
  'name' => clienttranslate("Discard Card from Hand"),
  'params' => 'target',
  'prompt' => '${you} must select a card to discard',
],
 'op_sell' => [  //
  'undo' => 'true',
  'type' => 'sell',
  'name' => clienttranslate("Discard Card from Hand to gain MC"),
  'params' => 'target',
  'prompt' => '${you} must select a card to discard to gain 1 MC|',
],
 'op_pass' => [  //
  'undo' => 'false',
  'type' => 'pass',
  'name' => clienttranslate("Pass"),
],
 'op_draw' => [  //
  'undo' => 'false',
  'type' => 'draw',
  'name' => clienttranslate("Draw Card in Hand"),
  'params' => 'auto',
],
// #auto-resolve actions
 'op_m' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationInc',
  'type' => 'm',
  'name' => clienttranslate("Gain M€"),
],
 'op_s' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationInc',
  'type' => 's',
  'name' => clienttranslate("Gain Steel"),
],
 'op_p' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationInc',
  'type' => 'p',
  'name' => clienttranslate("Gain Plant"),
],
 'op_e' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationInc',
  'type' => 'e',
  'name' => clienttranslate("Gain Energy"),
],
 'op_h' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationInc',
  'type' => 'h',
  'name' => clienttranslate("Gain Heat"),
],
 'op_u' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationInc',
  'type' => 'u',
  'name' => clienttranslate("Gain Titanium"),
],
 'op_nm' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationIncNeg',
  'type' => 'nm',
  'name' => clienttranslate("Pay M€"),
],
 'op_ns' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationIncNeg',
  'type' => 'ns',
  'name' => clienttranslate("Pay Steel"),
],
 'op_nu' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationIncNeg',
  'type' => 'nu',
  'name' => clienttranslate("Pay Titanium"),
],
 'op_np' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationIncNeg',
  'type' => 'np',
  'name' => clienttranslate("Pay Plant"),
],
 'op_ne' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationIncNeg',
  'type' => 'ne',
  'name' => clienttranslate("Pay Energy"),
],
 'op_nh' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationIncNeg',
  'type' => 'nh',
  'name' => clienttranslate("Pay Heat"),
],
 'op_pm' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationProd',
  'type' => 'pm',
  'name' => clienttranslate("Increase M€ Production"),
],
 'op_pu' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationProd',
  'type' => 'pu',
  'name' => clienttranslate("Increase Titanium Production"),
],
 'op_ps' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationProd',
  'type' => 'ps',
  'name' => clienttranslate("Increase Steel Production"),
],
 'op_pp' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationProd',
  'type' => 'pp',
  'name' => clienttranslate("Increase Plant Production"),
],
 'op_pe' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationProd',
  'type' => 'pe',
  'name' => clienttranslate("Increase Energy Production"),
],
 'op_ph' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationProd',
  'type' => 'ph',
  'name' => clienttranslate("Increase Heat Production"),
],
 'op_npm' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationProdNeg',
  'type' => 'npm',
  'name' => clienttranslate("Decrease M€ Production"),
],
 'op_npp' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationProdNeg',
  'type' => 'npp',
  'name' => clienttranslate("Decrease Plant Production"),
],
 'op_npe' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationProdNeg',
  'type' => 'npe',
  'name' => clienttranslate("Decrease Energy Production"),
],
 'op_nph' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationProdNeg',
  'type' => 'nph',
  'name' => clienttranslate("Decrease Heat Production"),
],
 'op_nps' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationProdNeg',
  'type' => 'nps',
  'name' => clienttranslate("Decrease Steel Production"),
],
 'op_npu' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationProdNeg',
  'type' => 'npu',
  'name' => clienttranslate("Decrease Titanium Production"),
],
 'op_o' => [  //
  'undo' => 'true',
  'type' => 'o',
  'name' => clienttranslate("Increase Oxigen Level"),
],
 'op_t' => [  //
  'undo' => 'true',
  'type' => 't',
  'name' => clienttranslate("Increase Temperature"),
],
 'op_turn' => [  //
  'undo' => 'true',
  'type' => 'turn',
  'name' => clienttranslate("Take a turn"),
],
 'op_tr' => [  //
  'undo' => 'true',
  'type' => 'tr',
  'name' => clienttranslate("Increase TR"),
],
 'op_research' => [  //
  'undo' => 'true',
  'type' => 'research',
  'name' => clienttranslate("Research"),
],
/* --- gen php end op_material --- */

/* --- gen php begin tracker_material --- */
// #counters
 'tracker_passed' => [  //
  'type' => 'tracker',
  'create' => 4,
  'location' => 'miniboard_{COLOR}',
  'name' => clienttranslate("Player Passed"),
  'state' => 0,
],
 'tracker_tr' => [  //
  'type' => 'tracker',
  'create' => 4,
  'location' => 'miniboard_{COLOR}',
  'name' => clienttranslate("TR"),
  'state' => 20,
],
 'tracker_pm' => [  //
  'type' => 'tracker',
  'create' => 4,
  'location' => 'miniboard_{COLOR}',
  'name' => clienttranslate("MC Production"),
  'state' => 1,
  'min'=>-5,
],
 'tracker_m' => [  //
  'type' => 'tracker',
  'create' => 4,
  'location' => 'miniboard_{COLOR}',
  'name' => clienttranslate("MC"),
  'state' => 42,
],
 'tracker_ps' => [  //
  'type' => 'tracker',
  'create' => 4,
  'location' => 'miniboard_{COLOR}',
  'name' => clienttranslate("Steel Production"),
  'state' => 1,
],
 'tracker_s' => [  //
  'type' => 'tracker',
  'create' => 4,
  'location' => 'miniboard_{COLOR}',
  'name' => clienttranslate("Steel"),
  'state' => 0,
],
 'tracker_pu' => [  //
  'type' => 'tracker',
  'create' => 4,
  'location' => 'miniboard_{COLOR}',
  'name' => clienttranslate("Titanium Production"),
  'state' => 1,
],
 'tracker_u' => [  //
  'type' => 'tracker',
  'create' => 4,
  'location' => 'miniboard_{COLOR}',
  'name' => clienttranslate("Titanium"),
  'state' => 0,
],
 'tracker_pp' => [  //
  'type' => 'tracker',
  'create' => 4,
  'location' => 'miniboard_{COLOR}',
  'name' => clienttranslate("Plant Production"),
  'state' => 1,
],
 'tracker_p' => [  //
  'type' => 'tracker',
  'create' => 4,
  'location' => 'miniboard_{COLOR}',
  'name' => clienttranslate("Plant"),
  'state' => 0,
],
 'tracker_pe' => [  //
  'type' => 'tracker',
  'create' => 4,
  'location' => 'miniboard_{COLOR}',
  'name' => clienttranslate("Energy Production"),
  'state' => 1,
],
 'tracker_e' => [  //
  'type' => 'tracker',
  'create' => 4,
  'location' => 'miniboard_{COLOR}',
  'name' => clienttranslate("Energy"),
  'state' => 0,
],
 'tracker_ph' => [  //
  'type' => 'tracker',
  'create' => 4,
  'location' => 'miniboard_{COLOR}',
  'name' => clienttranslate("Heat Production"),
  'state' => 1,
],
 'tracker_h' => [  //
  'type' => 'tracker',
  'create' => 4,
  'location' => 'miniboard_{COLOR}',
  'name' => clienttranslate("Heat"),
  'state' => 0,
],
// #terraforming parameters
 'tracker_o' => [  //
  'type' => 'param',
  'create' => 1,
  'location' => 'params',
  'name' => clienttranslate("Oxigen Level"),
  'state' => 0,
  'max'=>14,
],
 'tracker_t' => [  //
  'type' => 'param',
  'create' => 1,
  'location' => 'params',
  'name' => clienttranslate("Temperature"),
  'state' => -30,
  'max'=>8,'min'=>-30,
],
 'tracker_w' => [  //
  'type' => 'param',
  'create' => 1,
  'location' => 'params',
  'name' => clienttranslate("Oceans"),
  'state' => 0,
  'max'=>9,
],
/* --- gen php end tracker_material --- */
];



