<?php
/**
 *------
 * BGA framework: © Gregory Isabelli <gisabelli@boardgamearena.com> & Emmanuel Colin <ecolin@boardgamearena.com>
 * mars implementation : © Alena Laskavaia <laskava@gmail.com>
 * 
 * This code has been produced on the BGA studio platform for use on http://boardgamearena.com.
 * See http://en.boardgamearena.com/#!doc/Studio for more information.
 * -----
 *
 * material.inc.php
 *
 * mars game material description
 *
 * Here, you can describe the material of your game with PHP variables.
 *   
 * This file is loaded in your game logic class constructor, ie these variables
 * are available everywhere in your game logic code.
 * 
 * 
 * GENERATED CODE DO NOT EDIT MANAULLY
 *
 */

$this->token_types = [
/* --- gen php begin cards_material --- */
// #project cards, t is color type 1 - green, 2 - blue, 3 - event, 0 - stanard project, 4 - corp, 5 - prelude
 'card_main_1' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 1,
  'name' => clienttranslate("Colonizer Training Camp"),
  't' => 1,
  'cost' => 8,
  'pre' => 'o<=5',
  'tags' => 'Building Jovian',
  'text' => clienttranslate("Oxygen must be 5% or less."),
    'vp' => '2',
],
 'card_main_2' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 2,
  'name' => clienttranslate("Asteroid Mining Consortium"),
  't' => 1,
  'r' => 'Ref_u',
  'cost' => 13,
  'tags' => 'Jovian',
  'text' => clienttranslate("Requires that you have titanium production. Decrease any titanium production 1 step and increase your own 1 step."),
    'vp' => '1',
],
 'card_main_3' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 3,
  'name' => clienttranslate("Deep Well Heating"),
  't' => 1,
  'r' => 'pe,t',
  'cost' => 13,
  'tags' => 'Building Energy',
  'text' => clienttranslate("Increase your energy production 1 step. Increase temperature 1 step."),
],
 'card_main_4' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 4,
  'name' => clienttranslate("Cloud Seeding"),
  't' => 1,
  'r' => '1npm,2pp,Ref_ph',
  'cost' => 11,
  'pre' => 'w>=3',
  'text' => clienttranslate("Requires 3 ocean tiles. Decrease your MC production 1 step and any heat production 1 step.  Increase your plant production 2 steps."),
],
 'card_main_5' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 5,
  'name' => clienttranslate("Search For Life"),
  't' => 2,
  'r' => 'Ref_m',
  'cost' => 3,
  'pre' => 'o<=6',
  'tags' => 'Science',
  'ac' => clienttranslate("Action: Spend 1 MC to reveal and discard the top card of the draw deck. If that card has a microbe tag, add a science resource here."),
  'text' => clienttranslate("Oxygen must be 6% or less. 3 VPs if you have one or more science resource here."),
],
 'card_main_6' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 6,
  'name' => clienttranslate("Inventors' Guild"),
  't' => 2,
  'cost' => 9,
  'tags' => 'Science',
  'ac' => clienttranslate("Action: Look at the top card and either buy it or discard it"),
],
 'card_main_7' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 7,
  'name' => clienttranslate("Martian Rails"),
  't' => 2,
  'r' => 'Ref_m,Ref_e',
  'cost' => 13,
  'tags' => 'Building',
  'ac' => clienttranslate("Action: Spend 1 energy to gain 1 MC for each city tile ON MARS."),
],
 'card_main_8' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 8,
  'name' => clienttranslate("Capital"),
  't' => 1,
  'r' => '5pm,2npe',
  'cost' => 26,
  'pre' => 'w>=4',
  'tags' => 'Building City',
  'text' => clienttranslate("Requires 4 ocean tiles. Place [the capital city] tile. Decrease your energy production 2 steps and increase your MC production 5 steps. 1 ADDITIONAL VP FOR EACH OCEAN TILE ADJACENT TO THIS CITY TILE."),
],
 'card_main_9' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 9,
  'name' => clienttranslate("Asteroid"),
  't' => 3,
  'r' => '2u,3npAny,t',
  'cost' => 14,
  'tags' => 'Space Event',
  'text' => clienttranslate("Raise temperature 1 step and gain 2 titanium. Remove up to 3 plants from any player."),
],
 'card_main_10' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 10,
  'name' => clienttranslate("Comet"),
  't' => 3,
  'r' => '3npAny,t,w',
  'cost' => 21,
  'tags' => 'Space Event',
  'text' => clienttranslate("Raise temperature 1 step and place an ocean tile. Remove up to 3 plants from any player."),
],
 'card_main_11' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 11,
  'name' => clienttranslate("Big Asteroid"),
  't' => 3,
  'r' => '4u,4npAny,2t',
  'cost' => 27,
  'tags' => 'Space Event',
  'text' => clienttranslate("Raise temperature 2 steps and gain 4 titanium. Remove up to 4 plants from any player."),
],
 'card_main_12' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 12,
  'name' => clienttranslate("Water Import From Europa"),
  't' => 2,
  'r' => 'Ref_m,Ref_u,Ref_w',
  'cost' => 25,
  'tags' => 'Space Jovian',
  'ac' => clienttranslate("Action: Pay 12 MC to place an ocean tile. TITANIUM MAY BE USED as if playing a space card."),
  'text' => clienttranslate("1 VP for each Jovian tag you have."),
],
 'card_main_13' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 13,
  'name' => clienttranslate("Space Elevator"),
  't' => 2,
  'r' => 'pu,Ref_m,Ref_s',
  'cost' => 27,
  'tags' => 'Building Space',
  'ac' => clienttranslate("Action: Spend 1 steel to gain 5 MC"),
  'text' => clienttranslate("Increase your titanium production 1 step."),
    'vp' => '2',
],
 'card_main_14' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 14,
  'name' => clienttranslate("Development Center"),
  't' => 2,
  'r' => 'Ref_e',
  'cost' => 11,
  'tags' => 'Science Building',
  'ac' => clienttranslate("Action: Spend 1 energy to draw a card."),
],
 'card_main_15' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 15,
  'name' => clienttranslate("Equatorial Magnetizer"),
  't' => 2,
  'r' => 'Ref_pe,Ref_tr',
  'cost' => 11,
  'tags' => 'Building',
  'ac' => clienttranslate("Action: Decrease your energy production 1 step to increase your terraforming rating 1 step."),
],
 'card_main_16' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 16,
  'name' => clienttranslate("Domed Crater"),
  't' => 1,
  'r' => '3pm,1npe,3p',
  'cost' => 24,
  'pre' => 'o<=7',
  'tags' => 'Building City',
  'text' => clienttranslate("Oxygen must be 7% or less. Gain 3 plants and place a city tile. Decrease your energy production 1 step and increase MC production 3 steps."),
    'vp' => '1',
],
 'card_main_17' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 17,
  'name' => clienttranslate("Noctis City"),
  't' => 1,
  'r' => '3pm,1npe',
  'cost' => 18,
  'tags' => 'Building City',
  'text' => clienttranslate("Decrease your energy production 1 step and increase your MC production 3 steps. Place a tile ON THE RESERVED AREA, disregarding normal placement restrictions."),
],
 'card_main_18' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 18,
  'name' => clienttranslate("Methane From Titan"),
  't' => 1,
  'r' => '2pp,2ph',
  'cost' => 28,
  'pre' => 'o>=2',
  'tags' => 'Space Jovian',
  'text' => clienttranslate("Requires 2% oxygen. Increase your heat production 2 steps and your plant production 2 steps."),
    'vp' => '2',
],
 'card_main_19' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 19,
  'name' => clienttranslate("Imported Hydrogen"),
  't' => 3,
  'r' => 'Ref_p,w',
  'cost' => 16,
  'tags' => 'Space Earth Event',
  'text' => clienttranslate("Gain 3 plants, or add 3 microbes or 2 animals to ANOTHER card. Place an ocean tile."),
],
 'card_main_20' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 20,
  'name' => clienttranslate("Research Outpost"),
  't' => 2,
  'cost' => 18,
  'tags' => 'Science Building City',
  'ac' => clienttranslate("Effect: When you play a card, you pay 1 MC less for it."),
  'text' => clienttranslate("Place a city tile NEXT TO NO OTHER TILE."),
],
 'card_main_21' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 21,
  'name' => clienttranslate("Phobos Space Haven"),
  't' => 1,
  'r' => 'pu',
  'cost' => 25,
  'tags' => 'Space City',
  'text' => clienttranslate("Increase your titanium production 1 step and place a city tile ON THE RESERVED AREA."),
    'vp' => '3',
],
 'card_main_22' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 22,
  'name' => clienttranslate("Black Polar Dust"),
  't' => 1,
  'r' => '2npm,3ph,w',
  'cost' => 15,
  'text' => clienttranslate("Place an ocean tile. Decrease your MC production 2 steps and increase your heat production 3 steps."),
],
 'card_main_23' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 23,
  'name' => clienttranslate("Arctic Algae"),
  't' => 2,
  'r' => 'Ref_p',
  'cost' => 12,
  'pre' => 't<=-12',
  'tags' => 'Plant',
  'ac' => clienttranslate("Effect: When anyone places an ocean tile, gain 2 plants."),
  'text' => clienttranslate("It must be -12°C or colder to play. Gain 1 plant."),
],
 'card_main_24' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 24,
  'name' => clienttranslate("Predators"),
  't' => 2,
  'cost' => 14,
  'pre' => 'o>=11',
  'tags' => 'Animal',
  'ac' => clienttranslate("Action: Remove 1 animal from any card and add it to this card."),
  'text' => clienttranslate("Requires 11% oxygen. 1 VP per animal on this card."),
],
 'card_main_25' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 25,
  'name' => clienttranslate("Space Station"),
  't' => 2,
  'cost' => 10,
  'tags' => 'Space',
  'ac' => clienttranslate("Effect: When you play a space card, you pay 2 MC less for it."),
    'vp' => '1',
],
 'card_main_26' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 26,
  'name' => clienttranslate("Eos Chasma National Park"),
  't' => 1,
  'r' => '2pm,3p',
  'cost' => 16,
  'pre' => 't>=-12',
  'tags' => 'Building Plant',
  'text' => clienttranslate("Requires -128°C  or warmer. Add 1 animal TO ANY ANIMAL CARD. Gain 3 plants. Increase your MC production 2 steps."),
    'vp' => '1',
],
 'card_main_27' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 27,
  'name' => clienttranslate("Interstellar Colony Ship"),
  't' => 3,
  'cost' => 24,
  'tags' => 'Space Earth Event',
  'text' => clienttranslate("Requires 5 science tags."),
    'vp' => '4',
],
 'card_main_28' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 28,
  'name' => clienttranslate("Security Fleet"),
  't' => 2,
  'r' => 'Ref_u',
  'cost' => 12,
  'tags' => 'Space',
  'ac' => clienttranslate("Action: Spend 1 titanium to add 1 fighter resource to this card."),
  'text' => clienttranslate("1 VP for each fighter resource on this card."),
],
 'card_main_29' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 29,
  'name' => clienttranslate("Cupola City"),
  't' => 1,
  'r' => '3pm,1npe',
  'cost' => 16,
  'pre' => 'o<=9',
  'tags' => 'Building City',
  'text' => clienttranslate("Oxygen must be 9% or less. Place a city tile. Decrease your energy production 1 step and increase your MC production 3 steps."),
],
 'card_main_30' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 30,
  'name' => clienttranslate("Lunar Beam"),
  't' => 1,
  'r' => '2npm,2pe,2ph',
  'cost' => 13,
  'tags' => 'Earth Energy',
  'text' => clienttranslate("Decrease your MC production 2 steps and increase your heat production and energy production 2 steps each."),
],
 'card_main_31' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 31,
  'name' => clienttranslate("Optimal Aerobraking"),
  't' => 2,
  'cost' => 7,
  'tags' => 'Space',
  'ac' => clienttranslate("Effect: When you place a space event, you gain 3 MC and 3 heat."),
],
 'card_main_32' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 32,
  'name' => clienttranslate("Underground City"),
  't' => 1,
  'r' => '2ps,2npe',
  'cost' => 18,
  'tags' => 'Building City',
  'text' => clienttranslate("Place a city tile. Decrease your energy production 2 steps and increase your steel production 2 steps."),
],
 'card_main_33' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 33,
  'name' => clienttranslate("Regolith Eaters"),
  't' => 2,
  'r' => 'Ref_o',
  'cost' => 13,
  'tags' => 'Science Microbe',
  'ac' => clienttranslate("Action: Add 1 microbe to this card, or remove 2 microbe from this card to raise oxygen level 1 step."),
],
 'card_main_34' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 34,
  'name' => clienttranslate("GHG Producing Bacteria"),
  't' => 2,
  'r' => 'Ref_t',
  'cost' => 8,
  'pre' => 'o>=4',
  'tags' => 'Science Microbe',
  'ac' => clienttranslate("Action: Add 1 microbe to this card, or remove 2 microbes to raise temperature 1 step."),
  'text' => clienttranslate("Requires 4% oxygen."),
],
 'card_main_35' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 35,
  'name' => clienttranslate("Ants"),
  't' => 2,
  'cost' => 9,
  'pre' => 'o>=4',
  'tags' => 'Microbe',
  'ac' => clienttranslate("Action: Remove 1 microbe from any card to add 1 to this card."),
  'text' => clienttranslate("Requires 4% oxygen. 1 VP per 2 microbes on this card."),
],
 'card_main_36' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 36,
  'name' => clienttranslate("Release of Inert Gases"),
  't' => 3,
  'r' => '2tr',
  'cost' => 14,
  'tags' => 'Event',
  'text' => clienttranslate("Raise your terraform rating 2 steps."),
],
 'card_main_37' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 37,
  'name' => clienttranslate("Nitrogen-Rich Asteroid"),
  't' => 3,
  'r' => 'Ref_pp,2tr,t',
  'cost' => 31,
  'tags' => 'Space Event',
  'text' => clienttranslate("Raise your terraforming rating 2 steps and temperature 1 step. Increase your plant production 1 step, or 4 steps if you have 3 plant tags."),
],
 'card_main_38' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 38,
  'name' => clienttranslate("Rover Construction"),
  't' => 2,
  'r' => 'Ref_m',
  'cost' => 8,
  'tags' => 'Building',
  'ac' => clienttranslate("Effect: When any city tile is placed, gain 2 MC"),
    'vp' => '1',
],
 'card_main_39' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 39,
  'name' => clienttranslate("Deimos Down"),
  't' => 3,
  'r' => '4s,8npAny,3t',
  'cost' => 31,
  'tags' => 'Space Event',
  'text' => clienttranslate("Raise temperature 3 steps and gain 4 steel. Remove up to 8 plants from any player."),
],
 'card_main_40' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 40,
  'name' => clienttranslate("Asteroid Mining"),
  't' => 1,
  'r' => '2pu',
  'cost' => 30,
  'tags' => 'Space Jovian',
  'text' => clienttranslate("Increase your titanium production 2 steps."),
    'vp' => '2',
],
 'card_main_41' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 41,
  'name' => clienttranslate("Food Factory"),
  't' => 1,
  'r' => '4pm,1npp',
  'cost' => 12,
  'tags' => 'Building',
  'text' => clienttranslate("Decrease your plant production 1 step and increase your MC production 4 steps."),
    'vp' => '1',
],
 'card_main_42' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 42,
  'name' => clienttranslate("Archaebacteria"),
  't' => 1,
  'r' => 'pp',
  'cost' => 6,
  'pre' => 't<=-18',
  'tags' => 'Microbe',
  'text' => clienttranslate("It must be -18°C or colder. Increase your plant production 1 step."),
],
 'card_main_43' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 43,
  'name' => clienttranslate("Carbonate Processing"),
  't' => 1,
  'r' => '1npe,3ph',
  'cost' => 6,
  'tags' => 'Building',
  'text' => clienttranslate("Decrease your energy production 1 step and increase your heat production 3 steps."),
],
 'card_main_44' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 44,
  'name' => clienttranslate("Natural Preserve"),
  't' => 1,
  'r' => 'pm',
  'cost' => 9,
  'pre' => 'o<=4',
  'tags' => 'Science Building',
  'text' => clienttranslate("Oxygen must be 4% or less. Place this tile NEXT TO NO OTHER TILE. Increase your MC production 1 step."),
    'vp' => '1',
],
 'card_main_45' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 45,
  'name' => clienttranslate("Nuclear Power"),
  't' => 1,
  'r' => '2npm,3pe',
  'cost' => 10,
  'tags' => 'Building Energy',
  'text' => clienttranslate("Decrease your MC production 2 steps and increase your energy production 3 steps."),
],
 'card_main_46' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 46,
  'name' => clienttranslate("Lightning Harvest"),
  't' => 1,
  'r' => 'pm,pe',
  'cost' => 8,
  'tags' => 'Energy',
  'text' => clienttranslate("Requires 3 science tags. Increase your energy production and your MC production 1 step each."),
    'vp' => '1',
],
 'card_main_47' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 47,
  'name' => clienttranslate("Algae"),
  't' => 1,
  'r' => '2pp,p',
  'cost' => 10,
  'pre' => 'w>=5',
  'tags' => 'Plant',
  'text' => clienttranslate("Requires 5 ocean tiles. Gain 1 plant and increase your plant production 2 steps."),
],
 'card_main_48' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 48,
  'name' => clienttranslate("Adapted Lichen"),
  't' => 1,
  'r' => 'pp',
  'cost' => 9,
  'tags' => 'Plant',
  'text' => clienttranslate("Increase your plant production 1 step."),
],
 'card_main_49' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 49,
  'name' => clienttranslate("Tardigrades"),
  't' => 2,
  'cost' => 4,
  'tags' => 'Microbe',
  'ac' => clienttranslate("Action: Add 1 microbe to this card."),
  'text' => clienttranslate("1 VP per 4 microbes on this card."),
],
 'card_main_50' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 50,
  'name' => clienttranslate("Virus"),
  't' => 3,
  'cost' => 1,
  'tags' => 'Microbe Event',
  'text' => clienttranslate("Remove up to 2 animals or 5 plants from any player."),
],
 'card_main_51' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 51,
  'name' => clienttranslate("Miranda Resort"),
  't' => 1,
  'r' => 'Ref_pm',
  'cost' => 12,
  'tags' => 'Space Jovian',
  'text' => clienttranslate("Increase your MC production 1 step for each Earth tag you have."),
    'vp' => '1',
],
 'card_main_52' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 52,
  'name' => clienttranslate("Fish"),
  't' => 2,
  'r' => '1nppAny',
  'cost' => 9,
  'pre' => 't>=2',
  'tags' => 'Animal',
  'ac' => clienttranslate("Action: Add 1 animal to this card."),
  'text' => clienttranslate("Requires 2°C or warmer. Decrease any plant production 1 step. 1 VP for each animal on this card."),
],
 'card_main_53' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 53,
  'name' => clienttranslate("Lake Marineris"),
  't' => 1,
  'r' => '2w',
  'cost' => 18,
  'pre' => 't>=0',
  'text' => clienttranslate("Requires 0°C or warmer. Place 2 ocean tiles."),
    'vp' => '2',
],
 'card_main_54' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 54,
  'name' => clienttranslate("Small Animals"),
  't' => 2,
  'r' => '1nppAny',
  'cost' => 6,
  'pre' => 'o>=6',
  'tags' => 'Animal',
  'ac' => clienttranslate("Action: Add 1 animal to this card."),
  'text' => clienttranslate("Requires 6% oxygen. Decrease any plant production 1 step. 1 VP per 2 animals on this card."),
],
 'card_main_55' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 55,
  'name' => clienttranslate("Kelp Farming"),
  't' => 1,
  'r' => '2pm,3pp,2p',
  'cost' => 17,
  'pre' => 'w>=6',
  'text' => clienttranslate("Requires 6 ocean tiles. Increase your MC production 2 steps and your plant production 3 steps. Gain 2 plants."),
    'vp' => '1',
],
 'card_main_56' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 56,
  'name' => clienttranslate("Mine"),
  't' => 1,
  'r' => 'ps',
  'cost' => 4,
  'tags' => 'Building',
  'text' => clienttranslate("Increase your steel production 1 step."),
],
 'card_main_57' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 57,
  'name' => clienttranslate("Vesta Shipyard"),
  't' => 1,
  'r' => 'pu',
  'cost' => 15,
  'tags' => 'Space Jovian',
  'text' => clienttranslate("Increase your titanium production 1 step."),
    'vp' => '1',
],
 'card_main_58' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 58,
  'name' => clienttranslate("Beam From a Thorium Asteroid"),
  't' => 1,
  'r' => '3pe,3ph',
  'cost' => 32,
  'tags' => 'Space Jovian Energy',
  'text' => clienttranslate("Requires a Jovian tag. Increase your heat production and energy production 3 steps each."),
    'vp' => '1',
],
 'card_main_59' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 59,
  'name' => clienttranslate("Mangrove"),
  't' => 1,
  'r' => 'o',
  'cost' => 12,
  'pre' => 't>=4',
  'tags' => 'Plant',
  'text' => clienttranslate("Requires +4°C or warmer. Place a Greenery tile ON AN AREA RESERVED FOR OCEAN and raise oxygen 1 step. Disregard normal placement restrictions for this."),
    'vp' => '1',
],
 'card_main_60' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 60,
  'name' => clienttranslate("Trees"),
  't' => 1,
  'r' => '3pp,p',
  'cost' => 13,
  'pre' => 't>=-4',
  'tags' => 'Plant',
  'text' => clienttranslate("Requires -4°C or warmer. Increase your plant production 3 steps. Gain 1 plant."),
    'vp' => '1',
],
 'card_main_61' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 61,
  'name' => clienttranslate("Great Escarpment Consortium"),
  't' => 1,
  'r' => 'Ref_ps',
  'cost' => 6,
  'text' => clienttranslate("Requires that you have steel production. Decrease any steel production 1 step and increase your own 1 step"),
],
 'card_main_62' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 62,
  'name' => clienttranslate("Mineral Deposit"),
  't' => 3,
  'r' => '5s',
  'cost' => 5,
  'tags' => 'Event',
  'text' => clienttranslate("Gain 5 steel."),
],
 'card_main_63' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 63,
  'name' => clienttranslate("Mining Expedition"),
  't' => 3,
  'r' => '2s,2npAny,o',
  'cost' => 12,
  'tags' => 'Event',
  'text' => clienttranslate("Raise oxygen 1 step. Remove 2 plants from any player. Gain 2 steel."),
],
 'card_main_64' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 64,
  'name' => clienttranslate("Mining Area"),
  't' => 1,
  'r' => 'Ref_ps,Ref_pu',
  'cost' => 4,
  'tags' => 'Building',
  'text' => clienttranslate("Place [the mining] tile on an area with a steel or titanium placement bonus, adjacent to another of your tiles. Increase your production of that resource 1 step."),
],
 'card_main_65' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 65,
  'name' => clienttranslate("Building Industries"),
  't' => 1,
  'r' => '2ps,1npe',
  'cost' => 6,
  'tags' => 'Building',
  'text' => clienttranslate("Decrease your energy production 1 step and increase your steel production 2 steps."),
],
 'card_main_66' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 66,
  'name' => clienttranslate("Land Claim"),
  't' => 3,
  'cost' => 1,
  'tags' => 'Event',
  'text' => clienttranslate("Place your marker on a non-reserved area. Only you may place a tile here"),
],
 'card_main_67' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 67,
  'name' => clienttranslate("Mining Rights"),
  't' => 1,
  'r' => 'Ref_ps,Ref_pu',
  'cost' => 9,
  'tags' => 'Building',
  'text' => clienttranslate("Place [the mining] tile on an area with a steel or titanium placement bonus. Increase that production 1 step."),
],
 'card_main_68' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 68,
  'name' => clienttranslate("Sponsors"),
  't' => 1,
  'r' => '2pm',
  'cost' => 6,
  'tags' => 'Earth',
  'text' => clienttranslate("Increase your MC production 2  steps."),
],
 'card_main_69' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 69,
  'name' => clienttranslate("Electro Catapult"),
  't' => 2,
  'r' => '1npe,Ref_m,Ref_s,Ref_p',
  'cost' => 17,
  'pre' => 'o<=8',
  'tags' => 'Building',
  'ac' => clienttranslate("Action: Spend 1 plant or 1 steel to gain 7 MC"),
  'text' => clienttranslate("Oxygen must be 8% or less. Decrease your energy production 1 step."),
    'vp' => '1',
],
 'card_main_70' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 70,
  'name' => clienttranslate("Earth Catapult"),
  't' => 2,
  'cost' => 23,
  'tags' => 'Earth',
  'ac' => clienttranslate("Effect: when you play a card, you pay 2 MC less for it."),
    'vp' => '2',
],
 'card_main_71' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 71,
  'name' => clienttranslate("Advanced Alloys"),
  't' => 2,
  'cost' => 9,
  'tags' => 'Science',
  'ac' => clienttranslate("Effect: Each titanium you have is worth 1MC extra. Each steel you have is worth 1 MC extra."),
],
 'card_main_72' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 72,
  'name' => clienttranslate("Birds"),
  't' => 2,
  'r' => '2nppAny',
  'cost' => 10,
  'pre' => 'o>=13',
  'tags' => 'Animal',
  'ac' => clienttranslate("Action: Add an animal to this card."),
  'text' => clienttranslate("Requires 13% oxygen. Decrease any plant production 2 steps. 1 VP for each animal on this card"),
],
 'card_main_73' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 73,
  'name' => clienttranslate("Mars University"),
  't' => 2,
  'cost' => 8,
  'tags' => 'Science Building',
  'ac' => clienttranslate("Effect: When you play a science tag, including this, you may discard a card from hand to draw a card."),
    'vp' => '1',
],
 'card_main_74' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 74,
  'name' => clienttranslate("Viral Enhancers"),
  't' => 2,
  'cost' => 9,
  'tags' => 'Science Microbe',
  'ac' => clienttranslate("Effect: When you play a plant, microbe, or an animal tag, including this, gain 1 plant or add 1 resource TO THAT CARD."),
],
 'card_main_75' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 75,
  'name' => clienttranslate("Towing a Comet"),
  't' => 3,
  'r' => '2p,o,w',
  'cost' => 23,
  'tags' => 'Space Event',
  'text' => clienttranslate("Gain 2 plants. Raise oxygen level 1 step and place an ocean tile."),
],
 'card_main_76' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 76,
  'name' => clienttranslate("Space Mirrors"),
  't' => 2,
  'r' => 'Ref_pe,Ref_m',
  'cost' => 3,
  'tags' => 'Space Energy',
  'ac' => clienttranslate("Action: Spend 7MC to increase your energy production 1 step."),
],
 'card_main_77' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 77,
  'name' => clienttranslate("Solar Wind Power"),
  't' => 1,
  'r' => 'pe,2u',
  'cost' => 11,
  'tags' => 'Science Space Energy',
  'text' => clienttranslate("Increase your energy production 1 step and gain 2 titanium."),
],
 'card_main_78' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 78,
  'name' => clienttranslate("Ice Asteroid"),
  't' => 3,
  'r' => '2w',
  'cost' => 23,
  'tags' => 'Space Event',
  'text' => clienttranslate("Place 2 ocean tiles."),
],
 'card_main_79' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 79,
  'name' => clienttranslate("Quantum Extractor"),
  't' => 2,
  'r' => '4pe',
  'cost' => 13,
  'tags' => 'Science Energy',
  'ac' => clienttranslate("Effect: When you play a space card, you pay 2 MC less for it"),
],
 'card_main_80' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 80,
  'name' => clienttranslate("Giant Ice Asteroid"),
  't' => 3,
  'r' => '6npAny,2t,2w',
  'cost' => 36,
  'tags' => 'Space Event',
  'text' => clienttranslate("Raise temperature 2 steps and place 2 ocean tiles. Remove up to 6 plants from any plyer."),
],
 'card_main_81' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 81,
  'name' => clienttranslate("Ganymede Colony"),
  't' => 1,
  'cost' => 20,
  'tags' => 'Space City Jovian',
  'text' => clienttranslate("Place a city tile ON THE RESERVED AREA [for Ganymede Colony]. 1 VP per Jovian tag you have."),
],
 'card_main_82' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 82,
  'name' => clienttranslate("Callisto Penal Mines"),
  't' => 1,
  'r' => '3pm',
  'cost' => 24,
  'tags' => 'Space Jovian',
  'text' => clienttranslate("Increase your MC production 3 steps."),
    'vp' => '2',
],
 'card_main_83' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 83,
  'name' => clienttranslate("Giant Space Mirror"),
  't' => 1,
  'r' => '3pe',
  'cost' => 17,
  'tags' => 'Space Energy',
  'text' => clienttranslate("Increase your energy production 3 steps."),
],
 'card_main_84' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 84,
  'name' => clienttranslate("Trans-Neptune Probe"),
  't' => 1,
  'cost' => 6,
  'tags' => 'Science Space',
    'vp' => '1',
],
 'card_main_85' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 85,
  'name' => clienttranslate("Commercial District"),
  't' => 1,
  'r' => '4pm,1npe',
  'cost' => 16,
  'tags' => 'Building',
  'text' => clienttranslate("Decrease your energy production 1 step and increase your MC production 4 steps. Place [the commercial district] tile. 1 VP PER ADJACENT CITY TILE."),
],
 'card_main_86' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 86,
  'name' => clienttranslate("Robotic Workforce"),
  't' => 1,
  'r' => 'Ref_pm,Ref_ps,Ref_pu,Ref_pp,Ref_pe,Ref_ph',
  'cost' => 9,
  'tags' => 'Science',
  'text' => clienttranslate("Duplicate only the production box of one of your building cards."),
],
 'card_main_87' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 87,
  'name' => clienttranslate("Grass"),
  't' => 1,
  'r' => 'pp,3p',
  'cost' => 11,
  'pre' => 't>=-16',
  'tags' => 'Plant',
  'text' => clienttranslate("Requires -16°C or warmer. Increase your plant production 1 step. Gain 3 plants."),
],
 'card_main_88' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 88,
  'name' => clienttranslate("Heather"),
  't' => 1,
  'r' => 'pp,p',
  'cost' => 6,
  'pre' => 't>=-14',
  'tags' => 'Plant',
  'text' => clienttranslate("Requires -14°C or warmer. Increase your plant production 1 step. Gain 1 plant."),
],
 'card_main_89' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 89,
  'name' => clienttranslate("Peroxide Power"),
  't' => 1,
  'r' => '1npm,2pe',
  'cost' => 7,
  'tags' => 'Building Energy',
  'text' => clienttranslate("Decrease your MC production 1 step and increase your energy production 2 steps."),
],
 'card_main_90' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 90,
  'name' => clienttranslate("Research"),
  't' => 1,
  'cost' => 11,
  'tags' => 'Science',
  'text' => clienttranslate("Counts as playing 2 science cards. Draw 2 cards."),
    'vp' => '1',
],
 'card_main_91' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 91,
  'name' => clienttranslate("Gene Repair"),
  't' => 1,
  'r' => '2pm',
  'cost' => 12,
  'tags' => 'Science',
  'text' => clienttranslate("Requires 3 science tags. Increase your MC production 2 steps."),
    'vp' => '2',
],
 'card_main_92' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 92,
  'name' => clienttranslate("Io Mining Industries"),
  't' => 1,
  'r' => '2pm,2pu',
  'cost' => 41,
  'tags' => 'Space Jovian',
  'text' => clienttranslate("Increase your titanium production 2 steps and your MC production 2 steps. 1 VP per Jovian tag you have."),
],
 'card_main_93' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 93,
  'name' => clienttranslate("Bushes"),
  't' => 1,
  'r' => '2pp,2p',
  'cost' => 10,
  'pre' => 't>=-10',
  'tags' => 'Plant',
  'text' => clienttranslate("Requires -10°C or warmer. Increase your plant production 2 steps. Gain 2 plants."),
],
 'card_main_94' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 94,
  'name' => clienttranslate("Mass Converter"),
  't' => 2,
  'r' => '6pe',
  'cost' => 8,
  'tags' => 'Science Energy',
  'ac' => clienttranslate("Effect: When you play a space card, you pay 2 MC less for it."),
  'text' => clienttranslate("Requires 5 science tags. Increase your energy production 6 steps."),
],
 'card_main_95' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 95,
  'name' => clienttranslate("Physics Complex"),
  't' => 2,
  'r' => 'Ref_e',
  'cost' => 12,
  'tags' => 'Science Building',
  'ac' => clienttranslate("Action: Spend 6 energy to add a science resource to this card."),
  'text' => clienttranslate("2 VP for each science resource on this card."),
],
 'card_main_96' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 96,
  'name' => clienttranslate("Greenhouses"),
  't' => 1,
  'r' => 'Ref_p',
  'cost' => 6,
  'tags' => 'Building Plant',
  'text' => clienttranslate("Gain 1 plant for each city tile in play."),
],
 'card_main_97' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 97,
  'name' => clienttranslate("Nuclear Zone"),
  't' => 1,
  'r' => '2t',
  'cost' => 10,
  'tags' => 'Earth',
  'text' => clienttranslate("Place [the nuclear zone] tile and raise the temperature 2 steps."),
    'vp' => '-2',
],
 'card_main_98' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 98,
  'name' => clienttranslate("Tropical Resort"),
  't' => 1,
  'r' => '3pm,2nph',
  'cost' => 13,
  'tags' => 'Building',
  'text' => clienttranslate("Decrease your heat production 2 steps and increase your MC production 3 steps."),
    'vp' => '2',
],
 'card_main_99' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 99,
  'name' => clienttranslate("Toll Station"),
  't' => 1,
  'r' => 'Ref_pm',
  'cost' => 12,
  'tags' => 'Space',
  'text' => clienttranslate("Increase your MC production 1 step for each space tag your OPPONENTS have."),
],
 'card_main_100' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 100,
  'name' => clienttranslate("Fueled Generators"),
  't' => 1,
  'r' => '1npm,pe',
  'cost' => 1,
  'tags' => 'Building Energy',
  'text' => clienttranslate("Decrease your MC production 1 step and increase your energy production 1 step."),
],
 'card_main_101' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 101,
  'name' => clienttranslate("Ironworks"),
  't' => 2,
  'r' => 'Ref_s,Ref_e,Ref_o',
  'cost' => 11,
  'tags' => 'Building',
  'ac' => clienttranslate("Action: Spend 4 energy to gain 1 steel and increase oxygen 1 step."),
],
 'card_main_102' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 102,
  'name' => clienttranslate("Power Grid"),
  't' => 1,
  'r' => 'Ref_pe',
  'cost' => 18,
  'tags' => 'Energy',
  'text' => clienttranslate("Increase your energy production 1 step for each power tag you have, including this.)"),
],
 'card_main_103' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 103,
  'name' => clienttranslate("Steelworks"),
  't' => 2,
  'r' => 'Ref_s,Ref_e,Ref_o',
  'cost' => 15,
  'tags' => 'Building',
  'ac' => clienttranslate("Action: Spend 4 energy to gain 2 steel and increase oxygen 1 step."),
],
 'card_main_104' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 104,
  'name' => clienttranslate("Ore Processor"),
  't' => 2,
  'r' => 'Ref_u,Ref_p,Ref_o',
  'cost' => 13,
  'tags' => 'Building',
  'ac' => clienttranslate("Action: Spend 4 energy to gain 1 titanium and increase oxygen 1 step."),
],
 'card_main_105' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 105,
  'name' => clienttranslate("Earth Office"),
  't' => 2,
  'cost' => 1,
  'tags' => 'Earth',
  'ac' => clienttranslate("Effect: When you play an Earth tag, you pay 3 MC less for it."),
],
 'card_main_106' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 106,
  'name' => clienttranslate("Acquired Company"),
  't' => 1,
  'r' => '3pm',
  'cost' => 10,
  'tags' => 'Earth',
  'text' => clienttranslate("Increase your MC production 3 steps."),
],
 'card_main_107' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 107,
  'name' => clienttranslate("Media Archives"),
  't' => 1,
  'r' => 'Ref_m',
  'cost' => 8,
  'tags' => 'Earth',
  'text' => clienttranslate("Gain 1 MC for each event EVER PLAYED by all players"),
],
 'card_main_108' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 108,
  'name' => clienttranslate("Open City"),
  't' => 1,
  'r' => '4pm,1npe,2p',
  'cost' => 23,
  'pre' => 'o>=12',
  'tags' => 'Building City',
  'text' => clienttranslate("Requires 12% oxygen. Decrease your energy production 1 step and increase your MC production 4 steps. Gain 2 plants and place a city tile."),
    'vp' => '1',
],
 'card_main_109' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 109,
  'name' => clienttranslate("Media Group"),
  't' => 2,
  'r' => 'Ref_m',
  'cost' => 6,
  'tags' => 'Earth',
  'ac' => clienttranslate("Effect: After you play an event card, you gain 3MC"),
],
 'card_main_110' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 110,
  'name' => clienttranslate("Business Network"),
  't' => 2,
  'r' => '1npm',
  'cost' => 4,
  'tags' => 'Earth',
  'ac' => clienttranslate("Action: Look at the top card and either buy it or discard it"),
  'text' => clienttranslate("Decrease your MC production 1 step."),
],
 'card_main_111' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 111,
  'name' => clienttranslate("Business Contacts"),
  't' => 3,
  'cost' => 7,
  'tags' => 'Earth Event',
  'text' => clienttranslate("Look at the top 4 cards from the deck. Take 2 of them into hand and discard the other 2"),
],
 'card_main_112' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 112,
  'name' => clienttranslate("Bribed Committee"),
  't' => 3,
  'r' => '2tr',
  'cost' => 7,
  'tags' => 'Earth Event',
  'text' => clienttranslate("Raise your terraform rating 2 steps."),
    'vp' => '-2',
],
 'card_main_113' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 113,
  'name' => clienttranslate("Solar Power"),
  't' => 1,
  'r' => 'pe',
  'cost' => 11,
  'tags' => 'Building Energy',
  'text' => clienttranslate("Increase your energy production 1 step."),
    'vp' => '1',
],
 'card_main_114' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 114,
  'name' => clienttranslate("Breathing Filters"),
  't' => 1,
  'cost' => 11,
  'pre' => 'o>=7',
  'tags' => 'Science',
  'text' => clienttranslate("Requires 7% oxygen."),
    'vp' => '2',
],
 'card_main_115' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 115,
  'name' => clienttranslate("Artificial Photosynthesis"),
  't' => 1,
  'r' => 'Ref_pp,Ref_pe',
  'cost' => 12,
  'tags' => 'Science',
  'text' => clienttranslate("Increase your plant production 1 step or your energy production 2 steps."),
],
 'card_main_116' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 116,
  'name' => clienttranslate("Artificial Lake"),
  't' => 1,
  'r' => 'w',
  'cost' => 15,
  'pre' => 't>=-6',
  'tags' => 'Building',
  'text' => clienttranslate("Requires -6°C or warmer. Place 1 ocean tile ON AN AREA NOT RESERVED FOR OCEAN."),
    'vp' => '1',
],
 'card_main_117' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 117,
  'name' => clienttranslate("Geothermal Power"),
  't' => 1,
  'r' => '2pe',
  'cost' => 11,
  'tags' => 'Building Energy',
  'text' => clienttranslate("Increase your energy production 2 steps."),
],
 'card_main_118' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 118,
  'name' => clienttranslate("Farming"),
  't' => 1,
  'r' => '2pm,2pp,2p',
  'cost' => 16,
  'pre' => 't>=4',
  'tags' => 'Plant',
  'text' => clienttranslate("Requires +4°C or warmer. Increase your MC production 2 steps and your plant production 2 steps. Gain 2 plants."),
    'vp' => '2',
],
 'card_main_119' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 119,
  'name' => clienttranslate("Dust Seals"),
  't' => 1,
  'cost' => 2,
  'pre' => 'w<=3',
  'text' => clienttranslate("Requires 3 or less ocean tiles."),
    'vp' => '1',
],
 'card_main_120' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 120,
  'name' => clienttranslate("Urbanized Area"),
  't' => 1,
  'r' => '2pm,1npe',
  'cost' => 10,
  'tags' => 'Building City',
  'text' => clienttranslate("Decrease your energy production 1 step and increase your MC production 2 steps. Place a city tile ADJACENT TO AT LEAST 2 OTHER CITY TILES."),
],
 'card_main_121' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 121,
  'name' => clienttranslate("Sabotage"),
  't' => 3,
  'r' => 'Ref_m,Ref_s,Ref_u',
  'cost' => 1,
  'tags' => 'Event',
  'text' => clienttranslate("Remove up to 3 titanium from any player, or 4 steel, or 7 MC."),
],
 'card_main_122' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 122,
  'name' => clienttranslate("Moss"),
  't' => 1,
  'r' => 'pp,1np',
  'cost' => 4,
  'pre' => 'w>=3',
  'tags' => 'Plant',
  'text' => clienttranslate("Requires 3 ocean tiles and that you lose 1 plant. Increase your plant production 1 step."),
],
 'card_main_123' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 123,
  'name' => clienttranslate("Industrial Center"),
  't' => 2,
  'r' => 'Ref_ps,Ref_m',
  'cost' => 4,
  'tags' => 'Building',
  'ac' => clienttranslate("Action: Spend 7 MC to increase your steel production 1 step."),
  'text' => clienttranslate("Place [the Industrial Center] tile ADJACENT TO A CITY TILE."),
],
 'card_main_124' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 124,
  'name' => clienttranslate("Hired Raiders"),
  't' => 3,
  'r' => 'Ref_m,Ref_s',
  'cost' => 1,
  'tags' => 'Event',
  'text' => clienttranslate("Steal up to 2 steel, or 3MC from any player."),
],
 'card_main_125' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 125,
  'name' => clienttranslate("Hackers"),
  't' => 1,
  'r' => '2npmAny,1npe',
  'cost' => 3,
  'text' => clienttranslate("Decrease your energy production 1 step and any MC production 2 steps. Increase your MC production 2 steps."),
    'vp' => '-1',
],
 'card_main_126' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 126,
  'name' => clienttranslate("GHG Factories"),
  't' => 1,
  'r' => '1npe,4ph',
  'cost' => 11,
  'tags' => 'Building',
  'text' => clienttranslate("Decrease your energy production 1 step and increase your heat production 4 steps."),
],
 'card_main_127' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 127,
  'name' => clienttranslate("Subterranean Reservoir"),
  't' => 3,
  'r' => 'w',
  'cost' => 11,
  'tags' => 'Event',
  'text' => clienttranslate("Place 1 ocean tile."),
],
 'card_main_128' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 128,
  'name' => clienttranslate("Ecological Zone"),
  't' => 2,
  'cost' => 12,
  'tags' => 'Plant Animal',
  'ac' => clienttranslate("Effect: When you play an animal or a plant tag (including these 2), add an animal to this card."),
  'text' => clienttranslate("Requires that you have a greenery tile. Place [the Ecological Zone] tile ADJACENT TO ANY GREENERY TILE. 1 VP per 2 animals on this card."),
],
 'card_main_129' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 129,
  'name' => clienttranslate("Zeppelins"),
  't' => 1,
  'r' => 'Ref_pm',
  'cost' => 13,
  'pre' => 'o>=5',
  'text' => clienttranslate("Requires 5% oxygen. Increase your MC production 1 step for each city tile ON MARS."),
    'vp' => '1',
],
 'card_main_130' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 130,
  'name' => clienttranslate("Worms"),
  't' => 1,
  'r' => 'Ref_pp',
  'cost' => 8,
  'pre' => 'o>=4',
  'tags' => 'Microbe',
  'text' => clienttranslate("Requires 4% oxygen. Increase your plant production 1 step for every 2 microbe tags you have, including this."),
],
 'card_main_131' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 131,
  'name' => clienttranslate("Decomposers"),
  't' => 2,
  'cost' => 5,
  'pre' => 'o>=3',
  'tags' => 'Microbe',
  'ac' => clienttranslate("Effect: When you play an animal, plant, or microbe tag, including this, add a microbe to this card."),
  'text' => clienttranslate("Requires 3# oxygen. 1 VP per 3 microbes on this card."),
],
 'card_main_132' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 132,
  'name' => clienttranslate("Fusion Power"),
  't' => 1,
  'r' => '3pe',
  'cost' => 14,
  'tags' => 'Science Building Energy',
  'text' => clienttranslate("Requires 2 power tags. Increase your energy production 3 steps."),
],
 'card_main_133' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 133,
  'name' => clienttranslate("Symbiotic Fungus"),
  't' => 2,
  'cost' => 4,
  'pre' => 't>=-14',
  'tags' => 'Microbe',
  'ac' => clienttranslate("Action: Add a microbe to ANOTHER card."),
  'text' => clienttranslate("Requires -14°C or warmer."),
],
 'card_main_134' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 134,
  'name' => clienttranslate("Extreme-Cold Fungus"),
  't' => 2,
  'r' => 'Ref_p',
  'cost' => 13,
  'pre' => 't<=-10',
  'tags' => 'Microbe',
  'ac' => clienttranslate("Action: Gain 1 plant or add 2 microbes to ANOTHER card."),
  'text' => clienttranslate("It must be -10°C or colder."),
],
 'card_main_135' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 135,
  'name' => clienttranslate("Advanced Ecosystems"),
  't' => 1,
  'cost' => 11,
  'tags' => 'Microbe Plant Animal',
  'text' => clienttranslate("Requires a plant tag, a microbe tag, and an animal tag."),
    'vp' => '3',
],
 'card_main_136' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 136,
  'name' => clienttranslate("Great Dam"),
  't' => 1,
  'r' => '2pe',
  'cost' => 12,
  'pre' => 'w>=4',
  'tags' => 'Building Energy',
  'text' => clienttranslate("Requires 4 ocean tiles. Increase your energy production 2 steps."),
    'vp' => '1',
],
 'card_main_137' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 137,
  'name' => clienttranslate("Cartel"),
  't' => 1,
  'r' => 'Ref_pm',
  'cost' => 8,
  'tags' => 'Earth',
  'text' => clienttranslate("Increase your MC production 1 step for each Earth tag you have, including this."),
],
 'card_main_138' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 138,
  'name' => clienttranslate("Strip Mine"),
  't' => 1,
  'r' => '2ps,pu,2npe,2o',
  'cost' => 25,
  'tags' => 'Building',
  'text' => clienttranslate("Decrease your energy production 2 steps. Increase your steel production 2 steps and your titanium production 1 step. Raise oxygen 2 steps."),
],
 'card_main_139' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 139,
  'name' => clienttranslate("Wave Power"),
  't' => 1,
  'r' => 'pe',
  'cost' => 8,
  'pre' => 'w>=3',
  'tags' => 'Energy',
  'text' => clienttranslate("Requires 3 ocean tiles. Increase your energy production 1 step."),
    'vp' => '1',
],
 'card_main_140' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 140,
  'name' => clienttranslate("Lava Flows"),
  't' => 3,
  'r' => '2t',
  'cost' => 18,
  'tags' => 'Event',
  'text' => clienttranslate("Raise the temperature 2 steps and place this [the Lava Flow] tile ON EITHER THARSIS THOLUS, ASCRAEUS MONS, PAVONIS MONS OR ARSIA MONS."),
],
 'card_main_141' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 141,
  'name' => clienttranslate("Power Plant"),
  't' => 1,
  'r' => 'pe',
  'cost' => 4,
  'tags' => 'Building Energy',
  'text' => clienttranslate("Increase your energy production 1 step."),
],
 'card_main_142' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 142,
  'name' => clienttranslate("Mohole Area"),
  't' => 1,
  'r' => '4ph',
  'cost' => 20,
  'tags' => 'Building',
  'text' => clienttranslate("Increase your heat production 4 steps. Place [the Mohole Area] tile ON AN AREA RESERVED FOR OCEAN."),
],
 'card_main_143' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 143,
  'name' => clienttranslate("Large Convoy"),
  't' => 3,
  'r' => 'Ref_p,w',
  'cost' => 36,
  'tags' => 'Space Earth Event',
  'text' => clienttranslate("Place an ocean tile and draw 2 cards. Gain 5 plants, or add 4 animals to ANOTHER card."),
    'vp' => '2',
],
 'card_main_144' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 144,
  'name' => clienttranslate("Titanium Mine"),
  't' => 1,
  'r' => 'pu',
  'cost' => 7,
  'tags' => 'Building',
  'text' => clienttranslate("Increase your titanium production 1 step."),
],
 'card_main_145' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 145,
  'name' => clienttranslate("Tectonic Stress Power"),
  't' => 1,
  'r' => '3pe',
  'cost' => 18,
  'tags' => 'Building Energy',
  'text' => clienttranslate("Requires 2 science tags. Increase your energy production 3 steps."),
    'vp' => '1',
],
 'card_main_146' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 146,
  'name' => clienttranslate("Nitrophilic Moss"),
  't' => 1,
  'r' => '2pp,2np',
  'cost' => 8,
  'pre' => 'w>=3',
  'tags' => 'Plant',
  'text' => clienttranslate("Requires 3 ocean tiles and that you lose 2 plants. Increase your plant production 2 steps."),
],
 'card_main_147' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 147,
  'name' => clienttranslate("Herbivores"),
  't' => 2,
  'r' => 'Ref_pp',
  'cost' => 12,
  'pre' => 'o>=8',
  'tags' => 'Animal',
  'ac' => clienttranslate("Effect: When you place a greenery tile, add an animal to this card."),
  'text' => clienttranslate("Requires 8% oxygen. Add 1 animal to this card. Decrease any plant production 1 step. 1 VP per 2 animals on this card."),
],
 'card_main_148' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 148,
  'name' => clienttranslate("Insects"),
  't' => 1,
  'r' => 'Ref_pp',
  'cost' => 9,
  'pre' => 'o>=6',
  'tags' => 'Microbe',
  'text' => clienttranslate("Requires 6% oxygen. Increase your plant production 1 step for each plant tag you have."),
],
 'card_main_149' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 149,
  'name' => clienttranslate("CEO's Favourite Project"),
  't' => 3,
  'cost' => 1,
  'tags' => 'Event',
  'text' => clienttranslate("Add 1 resource to a card with at least 1 resource on it."),
],
 'card_main_150' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 150,
  'name' => clienttranslate("Anti-Gravity Technology"),
  't' => 2,
  'cost' => 14,
  'tags' => 'Science',
  'ac' => clienttranslate("Effect: when you play a card, you pay 2 MC less for it."),
  'text' => clienttranslate("Requires 7 science tags."),
    'vp' => '3',
],
 'card_main_151' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 151,
  'name' => clienttranslate("Investment Loan"),
  't' => 3,
  'r' => '1npm,10m',
  'cost' => 3,
  'tags' => 'Earth Event',
  'text' => clienttranslate("Decrease your MC production 1 step. Gain 10 MC."),
],
 'card_main_152' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 152,
  'name' => clienttranslate("Insulation"),
  't' => 1,
  'r' => 'Ref_pm,Ref_ph',
  'cost' => 2,
  'text' => clienttranslate("Decrease your heat production any number of steps and increase your MC production the same number of steps."),
],
 'card_main_153' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 153,
  'name' => clienttranslate("Adaptation Technology"),
  't' => 2,
  'cost' => 12,
  'tags' => 'Science',
  'ac' => clienttranslate("Effect: Your global requirements are +2 or -2 steps, your choice in each case."),
    'vp' => '1',
],
 'card_main_154' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 154,
  'name' => clienttranslate("Caretaker Contract"),
  't' => 2,
  'r' => 'Ref_h,Ref_tr',
  'cost' => 3,
  'pre' => 't>=0',
  'ac' => clienttranslate("Action: Spend 8 heat to increase your terraforming rating 1 step."),
  'text' => clienttranslate("Requires 0°C or warmer."),
],
 'card_main_155' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 155,
  'name' => clienttranslate("Designed Microorganisms"),
  't' => 1,
  'r' => '2pp',
  'cost' => 16,
  'pre' => 't<=-14',
  'tags' => 'Science Microbe',
  'text' => clienttranslate("It must be -14°C or colder. Increase your plant production 2 steps."),
],
 'card_main_156' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 156,
  'name' => clienttranslate("Standard Technology"),
  't' => 2,
  'cost' => 6,
  'tags' => 'Science',
  'ac' => clienttranslate("Effect: After you pay for a standard project, except selling patents, you gain 3 MC."),
],
 'card_main_157' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 157,
  'name' => clienttranslate("Nitrite Reducing Bacteria"),
  't' => 2,
  'r' => 'Ref_tr',
  'cost' => 11,
  'tags' => 'Microbe',
  'ac' => clienttranslate("Action: Add 1 microbe to this card, or remove 3 microbes to increase your TR 1 step."),
  'text' => clienttranslate("Add 3 microbes to this card."),
],
 'card_main_158' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 158,
  'name' => clienttranslate("Industrial Microbes"),
  't' => 1,
  'r' => 'ps,pe',
  'cost' => 12,
  'tags' => 'Building Microbe',
  'text' => clienttranslate("Increase your energy production and your steel production 1 step each."),
],
 'card_main_159' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 159,
  'name' => clienttranslate("Lichen"),
  't' => 1,
  'r' => 'pp',
  'cost' => 7,
  'pre' => 't>=-24',
  'tags' => 'Plant',
  'text' => clienttranslate("Requires -24°C or warmer. Increase your plant production 1 step."),
],
 'card_main_160' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 160,
  'name' => clienttranslate("Power Supply Consortium"),
  't' => 1,
  'r' => '1npeAny',
  'cost' => 5,
  'tags' => 'Energy',
  'text' => clienttranslate("Requires 2 power tags. Decrease any energy production 1 step and increase your own 1 step."),
],
 'card_main_161' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 161,
  'name' => clienttranslate("Convoy From Europa"),
  't' => 3,
  'r' => 'w',
  'cost' => 15,
  'tags' => 'Space Event',
  'text' => clienttranslate("Place 1 ocean tile and draw 1 card."),
],
 'card_main_162' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 162,
  'name' => clienttranslate("Imported GHG"),
  't' => 3,
  'r' => 'ph,3h',
  'cost' => 7,
  'tags' => 'Space Earth Event',
  'text' => clienttranslate("Increase your heat production 1 step and gain 3 hear."),
],
 'card_main_163' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 163,
  'name' => clienttranslate("Imported Nitrogen"),
  't' => 3,
  'r' => '4p,tr',
  'cost' => 23,
  'tags' => 'Space Earth Event',
  'text' => clienttranslate("Raise your TR 1 step and gain 4 plants. Add 3 microbes to ANOTHER card and 2 animals to ANOTHER card."),
],
 'card_main_164' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 164,
  'name' => clienttranslate("Micro-Mills"),
  't' => 1,
  'r' => 'ph',
  'cost' => 3,
  'text' => clienttranslate("Increase your heat production 1 step."),
],
 'card_main_165' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 165,
  'name' => clienttranslate("Magnetic Field Generators"),
  't' => 1,
  'r' => '2pp,4npe,3tr',
  'cost' => 20,
  'tags' => 'Building',
  'text' => clienttranslate("Decrease your energy production 4 steps and increase your plant production 2 steps. Raise your TR 3 steps."),
],
 'card_main_166' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 166,
  'name' => clienttranslate("Shuttles"),
  't' => 2,
  'r' => '2pm,1npe',
  'cost' => 10,
  'pre' => 'o>=5',
  'tags' => 'Space',
  'ac' => clienttranslate("Effect: When you play a space card, you pay 2MC less for it."),
  'text' => clienttranslate("Requires 5% oxygen. Decrease your energy production 1 step and increase your MC production 2 steps."),
    'vp' => '1',
],
 'card_main_167' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 167,
  'name' => clienttranslate("Import of Advanced GHG"),
  't' => 3,
  'r' => '2ph',
  'cost' => 9,
  'tags' => 'Space Earth Event',
  'text' => clienttranslate("Increase your heat production 2 steps."),
],
 'card_main_168' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 168,
  'name' => clienttranslate("Windmills"),
  't' => 1,
  'r' => 'pe',
  'cost' => 6,
  'pre' => 'o>=7',
  'tags' => 'Building Energy',
  'text' => clienttranslate("Requires 7% oxygen. Increase your energy production 1 step."),
    'vp' => '1',
],
 'card_main_169' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 169,
  'name' => clienttranslate("Tundra Farming"),
  't' => 1,
  'r' => '2pm,pp,p',
  'cost' => 16,
  'pre' => 't>=-6',
  'tags' => 'Plant',
  'text' => clienttranslate("Requires -6°C or warmer. Increase your plant production 1 step and your MC production 2 steps. Gain 1 plant."),
    'vp' => '2',
],
 'card_main_170' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 170,
  'name' => clienttranslate("Aerobraked Ammonia Asteroid"),
  't' => 3,
  'r' => 'pp,3ph',
  'cost' => 26,
  'tags' => 'Space Event',
  'text' => clienttranslate("Add 2 microbes to ANOTHER card. Increase your heat production 3 steps and your plant production 1 step."),
],
 'card_main_171' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 171,
  'name' => clienttranslate("Magnetic Field Dome"),
  't' => 1,
  'r' => 'pp,2npe,tr',
  'cost' => 5,
  'tags' => 'Building',
  'text' => clienttranslate("Decrease your energy production 2 steps and increase your plant production 1 step. Raise your terraform rating 1 step."),
],
 'card_main_172' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 172,
  'name' => clienttranslate("Pets"),
  't' => 2,
  'cost' => 10,
  'tags' => 'Animal Earth',
  'ac' => clienttranslate("Effect: When any city tile is placed, add an animal to this card.  Animals may not be removed from this card."),
  'text' => clienttranslate("Add 1 animal to this card. 1 VP per 2 animals here."),
],
 'card_main_173' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 173,
  'name' => clienttranslate("Protected Habitats"),
  't' => 2,
  'cost' => 5,
  'ac' => clienttranslate("[Effect: ]Opponents may not remove your [plants, animals or microbes]"),
],
 'card_main_174' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 174,
  'name' => clienttranslate("Protected Valley"),
  't' => 1,
  'r' => '2pm,o',
  'cost' => 23,
  'tags' => 'Building Plant',
  'text' => clienttranslate("Increase your MC production 2 steps. Place a greenery tile ON AN AREA RESERVED FOR OCEAN, disregarding normal placement restrictions, and increase oxygen 1 step."),
],
 'card_main_175' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 175,
  'name' => clienttranslate("Satellites"),
  't' => 1,
  'r' => 'Ref_pm',
  'cost' => 10,
  'tags' => 'Space',
  'text' => clienttranslate("Increase your MC production 1 step for each space tag you have, including this one."),
],
 'card_main_176' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 176,
  'name' => clienttranslate("Noctis Farming"),
  't' => 1,
  'r' => 'pm,2p',
  'cost' => 10,
  'pre' => 't>=-20',
  'tags' => 'Building Plant',
  'text' => clienttranslate("Requires -20°C or warmer. Increase your MC production 1 step and gain 2 plants."),
    'vp' => '1',
],
 'card_main_177' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 177,
  'name' => clienttranslate("Water Splitting Plant"),
  't' => 2,
  'r' => 'Ref_e,Ref_o',
  'cost' => 12,
  'pre' => 'w>=2',
  'tags' => 'Building',
  'ac' => clienttranslate("Action: Spend 3 energy to raise oxygen 1 step."),
  'text' => clienttranslate("Requires 2 ocean tiles."),
],
 'card_main_178' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 178,
  'name' => clienttranslate("Heat Trappers"),
  't' => 1,
  'r' => 'pe,Ref_h',
  'cost' => 6,
  'tags' => 'Building Energy',
  'text' => clienttranslate("Decrease any heat production 2 steps and increase your energy production 1 step."),
    'vp' => '-1',
],
 'card_main_179' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 179,
  'name' => clienttranslate("Soil Factory"),
  't' => 1,
  'r' => 'pp,1npe',
  'cost' => 9,
  'tags' => 'Building',
  'text' => clienttranslate("Decrease your energy production 1 step and increase your plant production 1 step."),
    'vp' => '1',
],
 'card_main_180' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 180,
  'name' => clienttranslate("Fuel Factory"),
  't' => 1,
  'r' => 'pm,pu,1npe',
  'cost' => 6,
  'tags' => 'Building',
  'text' => clienttranslate("Decreases your energy production 1 step and increase your titanium and your MC production 1 step each."),
],
 'card_main_181' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 181,
  'name' => clienttranslate("Ice cap Melting"),
  't' => 3,
  'r' => 'w',
  'cost' => 5,
  'pre' => 't>=2',
  'tags' => 'Event',
  'text' => clienttranslate("Requires +2°C or warmer. Place 1 ocean tile."),
],
 'card_main_182' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 182,
  'name' => clienttranslate("Corporate Stronghold"),
  't' => 1,
  'r' => '3pm,1npe',
  'cost' => 11,
  'tags' => 'Building City',
  'text' => clienttranslate("Decrease your energy production 1 step and increase your MC production 3 steps. Place a city tile."),
    'vp' => '-2',
],
 'card_main_183' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 183,
  'name' => clienttranslate("Biomass Combustors"),
  't' => 1,
  'r' => '1nppAny,2pe',
  'cost' => 4,
  'pre' => 'o>=6',
  'tags' => 'Building Energy',
  'text' => clienttranslate("Requires 6% oxygen. Decrease any plant production 1 step and increase your energy production 2 steps."),
    'vp' => '-1',
],
 'card_main_184' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 184,
  'name' => clienttranslate("Livestock"),
  't' => 2,
  'r' => '2pm,1npp',
  'cost' => 13,
  'pre' => 'o>=9',
  'tags' => 'Animal',
  'ac' => clienttranslate("Action: Add 1 animal to this card."),
  'text' => clienttranslate("Requires 9% oxygen. Decrease your plant production 1 step and increase your MC production 2 steps. 1 VP for each animal on this card."),
],
 'card_main_185' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 185,
  'name' => clienttranslate("Olympus Conference"),
  't' => 2,
  'cost' => 10,
  'tags' => 'Science Building Earth',
  'ac' => clienttranslate("Effect: When you play a science tag, including this, either add a science resource to this card, or remove a science resource from this card to draw a card."),
    'vp' => '1',
],
 'card_main_186' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 186,
  'name' => clienttranslate("Rad-Suits"),
  't' => 1,
  'r' => 'pm',
  'cost' => 6,
  'text' => clienttranslate("Requires 2 cities in play. Increase your MC production 1 step."),
    'vp' => '1',
],
 'card_main_187' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 187,
  'name' => clienttranslate("Aquifer Pumping"),
  't' => 2,
  'r' => 'Ref_m,Ref_s,Ref_w',
  'cost' => 18,
  'tags' => 'Building',
  'ac' => clienttranslate("Action: Spend 8 MC to place 1 ocean tile. STEEL MAY BE USED as if you were playing a building card."),
],
 'card_main_188' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 188,
  'name' => clienttranslate("Flooding"),
  't' => 3,
  'r' => 'Ref_m,w',
  'cost' => 7,
  'tags' => 'Event',
  'text' => clienttranslate("Place an ocean tile. IF THERE ARE TILES ADJACENT TO THIS OCEAN TILE, YOU MAY REMOVE 4 MC FROM THE OWNER OF ONE OF THOSE TILES."),
    'vp' => '-1',
],
 'card_main_189' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 189,
  'name' => clienttranslate("Energy Saving"),
  't' => 1,
  'r' => 'Ref_pe',
  'cost' => 15,
  'tags' => 'Energy',
  'text' => clienttranslate("Increase your energy production 1 step for each city tile in play."),
],
 'card_main_190' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 190,
  'name' => clienttranslate("Local Heat Trapping"),
  't' => 3,
  'r' => 'Ref_p,5nh',
  'cost' => 1,
  'tags' => 'Event',
  'text' => clienttranslate("Spend 5 heat to either gain 4 plants, or to add 2 animals to ANOTHER card."),
],
 'card_main_191' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 191,
  'name' => clienttranslate("Permafrost extraction"),
  't' => 3,
  'cost' => 8,
  'pre' => 't>=-8',
  'tags' => 'Event',
  'text' => clienttranslate("Requires -8°C or warmer. Place 1 ocean tile."),
],
 'card_main_192' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 192,
  'name' => clienttranslate("Invention Contest"),
  't' => 3,
  'cost' => 2,
  'tags' => 'Science Event',
  'text' => clienttranslate("Look at the top 3 cards from the deck. Take 1 of them into hand and discard the other 2"),
],
 'card_main_193' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 193,
  'name' => clienttranslate("Plantation"),
  't' => 1,
  'r' => 'o',
  'cost' => 15,
  'tags' => 'Plant',
  'text' => clienttranslate("Requires 2 science tags. Place a greenery tile and raise oxygen 1 step."),
],
 'card_main_194' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 194,
  'name' => clienttranslate("Power Infrastructure"),
  't' => 2,
  'r' => 'Ref_m,Ref_e',
  'cost' => 4,
  'tags' => 'Building Energy',
  'ac' => clienttranslate("Action: Spend any amount of energy to gain that amount of MC."),
],
 'card_main_195' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 195,
  'name' => clienttranslate("Indentured Workers"),
  't' => 3,
  'cost' => 0,
  'tags' => 'Event',
  'text' => clienttranslate("The next card you play this generation costs 8MC less."),
    'vp' => '-1',
],
 'card_main_196' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 196,
  'name' => clienttranslate("Lagrange Observatory"),
  't' => 1,
  'cost' => 9,
  'tags' => 'Science Space',
  'text' => clienttranslate("Draw 1 card."),
    'vp' => '1',
],
 'card_main_197' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 197,
  'name' => clienttranslate("Terraforming Ganymede"),
  't' => 1,
  'r' => 'Ref_tr',
  'cost' => 33,
  'tags' => 'Space Jovian',
  'text' => clienttranslate("Raise your TR 1 step for each Jovian tag you have, including this."),
    'vp' => '2',
],
 'card_main_198' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 198,
  'name' => clienttranslate("Immigration Shuttles"),
  't' => 1,
  'r' => '5pm',
  'cost' => 31,
  'tags' => 'Space Earth',
  'text' => clienttranslate("Increase your MC production 5 steps. 1 VP for every 3rd city in play."),
],
 'card_main_199' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 199,
  'name' => clienttranslate("Restricted Area"),
  't' => 2,
  'r' => 'Ref_m',
  'cost' => 11,
  'tags' => 'Science',
  'ac' => clienttranslate("Action: Spend 2MC to draw a card."),
  'text' => clienttranslate("Place [the restricted area] tile."),
],
 'card_main_200' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 200,
  'name' => clienttranslate("Immigrant City"),
  't' => 2,
  'r' => 'Ref_pm,1npe',
  'cost' => 13,
  'tags' => 'Building City',
  'ac' => clienttranslate("Effect: Each time a city tile is placed, including this, increase your MC production 1 step."),
  'text' => clienttranslate("Decrease your energy production 1 step and decrease your MC production 2 steps. Place a city tile."),
],
 'card_main_201' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 201,
  'name' => clienttranslate("Energy Tapping"),
  't' => 1,
  'r' => '1npeAny',
  'cost' => 3,
  'tags' => 'Energy',
  'text' => clienttranslate("Decrease any energy production 1 step and increase your own 1 step."),
    'vp' => '-1',
],
 'card_main_202' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 202,
  'name' => clienttranslate("Underground Detonations"),
  't' => 2,
  'r' => 'Ref_ph,Ref_m',
  'cost' => 6,
  'tags' => 'Building',
  'ac' => clienttranslate("Action: Spend 10 MC to increase your heat production 2 steps."),
],
 'card_main_203' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 203,
  'name' => clienttranslate("Soletta"),
  't' => 1,
  'r' => '7ph',
  'cost' => 35,
  'tags' => 'Space',
  'text' => clienttranslate("Increase your heat production 7 steps."),
],
 'card_main_204' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 204,
  'name' => clienttranslate("Technology Demonstration"),
  't' => 3,
  'cost' => 5,
  'tags' => 'Science Space Event',
  'text' => clienttranslate("Draw 2 cards."),
],
 'card_main_205' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 205,
  'name' => clienttranslate("Rad-Chem Factory"),
  't' => 1,
  'r' => '1npe,2tr',
  'cost' => 8,
  'tags' => 'Building',
  'text' => clienttranslate("Decrease your energy production 1 step. Raise your terraform rating 2 steps."),
],
 'card_main_206' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 206,
  'name' => clienttranslate("Special Design"),
  't' => 3,
  'cost' => 4,
  'tags' => 'Science Event',
  'text' => clienttranslate("The next card you play this generation is +2 or -2 in global requirements, your choice."),
],
 'card_main_207' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 207,
  'name' => clienttranslate("Medical Lab"),
  't' => 1,
  'r' => 'Ref_pm',
  'cost' => 13,
  'tags' => 'Science Building',
  'text' => clienttranslate("Increase your MC production 1 step for every 2 building tags you have, including this."),
    'vp' => '1',
],
 'card_main_208' => [  //
  'location' => 'deck_main',
  'create' => 'single',
  'num' => 208,
  'name' => clienttranslate("AI Central"),
  't' => 2,
  'r' => '1npe',
  'cost' => 21,
  'tags' => 'Science Building',
  'ac' => clienttranslate("Action: Draw 2 cards."),
  'text' => clienttranslate("Requires 3 science tags to play. Decrease your energy production 1 step."),
    'vp' => '1',
],
/* --- gen php end cards_material --- */
/* --- gen php begin proj_material --- */
// #corp cards
// #
 'card_corp_1' => [  //
  'location' => 'deck_corp',
  'num' => 1,
  'name' => clienttranslate("Begginer Corp"),
  't' => 4,
  'r' => '42m',
  'cost' => 10,
  'pre' => 'This is a begginer corp',
],
// #
// #standard projects
// #
 'card_stanproj_1' => [  //
  'location' => 'display_main',
  'count' => 1,
  'create' => 1,
  'num' => 1,
  'name' => clienttranslate("Sell patents"),
  't' => 0,
  'r' => '[1,](sell)',
  'cost' => 0,
  'text' => 'Discard X card to gain X MC',
],
 'card_stanproj_2' => [  //
  'location' => 'display_main',
  'count' => 1,
  'create' => 1,
  'num' => 2,
  'name' => clienttranslate("Power plant"),
  't' => 0,
  'r' => 'pe',
  'cost' => 11,
  'text' => 'For 11 M€ you get to increase your energy production 1 step',
],
 'card_stanproj_3' => [  //
  'location' => 'display_main',
  'count' => 1,
  'create' => 1,
  'num' => 3,
  'name' => clienttranslate("Asteroid"),
  't' => 0,
  'r' => 't',
  'cost' => 14,
  'text' => 'For 14 M€ you get to increase temperature 1 step (and your TR)',
],
 'card_stanproj_4' => [  //
  'location' => 'display_main',
  'count' => 1,
  'create' => 1,
  'num' => 4,
  'name' => clienttranslate("Aquifer"),
  't' => 0,
  'r' => 'w',
  'cost' => 18,
  'text' => 'For 18 M€ you get to place an ocean tile (you also get 1 TR and collect any placement bonus for the tile)',
],
 'card_stanproj_5' => [  //
  'location' => 'display_main',
  'count' => 1,
  'create' => 1,
  'num' => 5,
  'name' => clienttranslate("Greenery"),
  't' => 0,
  'r' => 'forest',
  'cost' => 23,
  'text' => 'For 23 M€ you get to place a greenery tile, which increases oxygen level (and your TR) 1 step, and collect any placement bonus for the tile. Put a player marker on the tile',
],
 'card_stanproj_6' => [  //
  'location' => 'display_main',
  'count' => 1,
  'create' => 1,
  'num' => 6,
  'name' => clienttranslate("City"),
  't' => 0,
  'r' => 'city;pm',
  'cost' => 25,
  'text' => 'For 25 M€ you get to place a city tile (collect any placement bonus for the tile, and place a player marker on it). You also get to increase your M€ production 1 step.',
],
/* --- gen php end proj_material --- */
/* --- gen php begin loc_material --- */
 'deck_main' => [  //
  'type' => 'location',
  'name' => clienttranslate("Main Deck"),
  'location' => 'main_area',
  'scope' => 'global',
  'counter' => 'public',
  'content' => 'hidden',
  'auto_resuffle'=>'discard_main',
],
 'deck_corp' => [  //
  'type' => 'location',
  'name' => clienttranslate("Corp Deck"),
  'location' => 'limbo',
  'scope' => 'global',
  'counter' => 'hidden',
  'content' => 'hidden',
],
 'discard_main' => [  //
  'type' => 'location',
  'name' => clienttranslate("Main Discard"),
  'location' => 'main_area',
  'scope' => 'global',
  'counter' => 'public',
  'content' => 'public',
],
 'hand' => [  //
  'type' => 'location',
  'name' => clienttranslate("Hand"),
  'location' => 'hand_area',
  'scope' => 'player',
  'counter' => 'public',
  'content' => 'private',
],
 'tableau' => [  //
  'type' => 'location',
  'name' => clienttranslate("Player Area"),
  'location' => 'tableau_area',
  'scope' => 'player',
  'counter' => 'public',
  'content' => 'public',
],
 'display_main' => [  //
  'type' => 'location',
  'name' => clienttranslate("Display"),
  'location' => 'main_area',
  'scope' => 'global',
  'counter' => 'public',
  'content' => 'public',
],
 'limbo' => [  //
  'type' => 'location',
  'name' => clienttranslate("Limbo"),
  'scope' => 'global',
  'counter' => 'hidden',
  'content' => 'hidden',
],
/* --- gen php end loc_material --- */

/* --- gen php begin op_material --- */
 'op_card' => [  //
  'undo' => 'true',
  'type' => 'card',
  'name' => clienttranslate("Play Card"),
  'params' => 'target,payment',
  'prompt' => '${you} must select a card to play',
],
 'op_stan' => [  //
  'undo' => 'true',
  'type' => 'stan',
  'name' => clienttranslate("Standard Project"),
  'params' => 'target,payment',
  'prompt' => '${you} must select a basic project to play',
],
// #x|Place Tile|target|${you} must select a location to place tile
 'op_w' => [  //
  'undo' => 'true',
  'type' => 'w',
  'name' => clienttranslate("Place Ocean Tile"),
  'params' => 'target',
  'prompt' => '${you} must select a location to place an ocean tile',
],
 'op_forest' => [  //
  'undo' => 'true',
  'type' => 'forest',
  'name' => clienttranslate("Place Forest Tile"),
  'params' => 'target',
  'prompt' => '${you} must select a location to place an forest tile, adjucent if possible',
],
 'op_city' => [  //
  'undo' => 'true',
  'type' => 'city',
  'name' => clienttranslate("Place City Tile"),
  'params' => 'target',
  'prompt' => '${you} must select a location to place a city, cannot place close to other city',
],
 'op_discard' => [  //
  'undo' => 'true',
  'type' => 'discard',
  'name' => clienttranslate("Discard Card from Hand"),
  'params' => 'target',
  'prompt' => '${you} must select a card to discard',
],
 'op_sell' => [  //
  'undo' => 'true',
  'type' => 'sell',
  'name' => clienttranslate("Discard Card from Hand to gain MC"),
  'params' => 'target',
  'prompt' => '${you} must select a card to discard to gain 1 MC|',
],
 'op_pass' => [  //
  'undo' => 'false',
  'type' => 'pass',
  'name' => clienttranslate("Pass"),
],
 'op_draw' => [  //
  'undo' => 'false',
  'type' => 'draw',
  'name' => clienttranslate("Draw Card in Hand"),
  'params' => 'auto',
],
// #auto-resolve actions
 'op_m' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationInc',
  'type' => 'm',
  'name' => clienttranslate("Gain M€"),
],
 'op_s' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationInc',
  'type' => 's',
  'name' => clienttranslate("Gain Steel"),
],
 'op_p' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationInc',
  'type' => 'p',
  'name' => clienttranslate("Gain Plant"),
],
 'op_e' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationInc',
  'type' => 'e',
  'name' => clienttranslate("Gain Energy"),
],
 'op_h' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationInc',
  'type' => 'h',
  'name' => clienttranslate("Gain Heat"),
],
 'op_u' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationInc',
  'type' => 'u',
  'name' => clienttranslate("Gain Titanium"),
],
 'op_nm' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationIncNeg',
  'type' => 'nm',
  'name' => clienttranslate("Pay M€"),
],
 'op_ns' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationIncNeg',
  'type' => 'ns',
  'name' => clienttranslate("Pay Steel"),
],
 'op_nu' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationIncNeg',
  'type' => 'nu',
  'name' => clienttranslate("Pay Titanium"),
],
 'op_np' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationIncNeg',
  'type' => 'np',
  'name' => clienttranslate("Pay Plant"),
],
 'op_ne' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationIncNeg',
  'type' => 'ne',
  'name' => clienttranslate("Pay Energy"),
],
 'op_nh' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationIncNeg',
  'type' => 'nh',
  'name' => clienttranslate("Pay Heat"),
],
 'op_pm' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationProd',
  'type' => 'pm',
  'name' => clienttranslate("Increase M€ Production"),
],
 'op_pu' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationProd',
  'type' => 'pu',
  'name' => clienttranslate("Increase Titanium Production"),
],
 'op_ps' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationProd',
  'type' => 'ps',
  'name' => clienttranslate("Increase Steel Production"),
],
 'op_pp' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationProd',
  'type' => 'pp',
  'name' => clienttranslate("Increase Plant Production"),
],
 'op_pe' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationProd',
  'type' => 'pe',
  'name' => clienttranslate("Increase Energy Production"),
],
 'op_ph' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationProd',
  'type' => 'ph',
  'name' => clienttranslate("Increase Heat Production"),
],
 'op_npm' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationProdNeg',
  'type' => 'npm',
  'name' => clienttranslate("Decrease M€ Production"),
],
 'op_npp' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationProdNeg',
  'type' => 'npp',
  'name' => clienttranslate("Decrease Plant Production"),
],
 'op_npe' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationProdNeg',
  'type' => 'npe',
  'name' => clienttranslate("Decrease Energy Production"),
],
 'op_nph' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationProdNeg',
  'type' => 'nph',
  'name' => clienttranslate("Decrease Heat Production"),
],
 'op_nps' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationProdNeg',
  'type' => 'nps',
  'name' => clienttranslate("Decrease Steel Production"),
],
 'op_npu' => [  //
  'undo' => 'true',
  'class' => 'AbsOperationProdNeg',
  'type' => 'npu',
  'name' => clienttranslate("Decrease Titanium Production"),
],
 'op_o' => [  //
  'undo' => 'true',
  'type' => 'o',
  'name' => clienttranslate("Increase Oxigen Level"),
],
 'op_t' => [  //
  'undo' => 'true',
  'type' => 't',
  'name' => clienttranslate("Increase Temperature"),
],
 'op_turn' => [  //
  'undo' => 'true',
  'type' => 'turn',
  'name' => clienttranslate("Take a turn"),
],
 'op_tr' => [  //
  'undo' => 'true',
  'type' => 'tr',
  'name' => clienttranslate("Increase TR"),
],
 'op_research' => [  //
  'undo' => 'true',
  'type' => 'research',
  'name' => clienttranslate("Research"),
],
/* --- gen php end op_material --- */

/* --- gen php begin tracker_material --- */
// #counters
 'tracker_passed' => [  //
  'type' => 'tracker',
  'create' => 4,
  'location' => 'miniboard_{COLOR}',
  'name' => clienttranslate("Player Passed"),
  'state' => 0,
],
 'tracker_tr' => [  //
  'type' => 'tracker',
  'create' => 4,
  'location' => 'miniboard_{COLOR}',
  'name' => clienttranslate("TR"),
  'state' => 20,
],
 'tracker_pm' => [  //
  'type' => 'tracker',
  'create' => 4,
  'location' => 'miniboard_{COLOR}',
  'name' => clienttranslate("MC Production"),
  'state' => 1,
  'min'=>-5,
],
 'tracker_m' => [  //
  'type' => 'tracker',
  'create' => 4,
  'location' => 'miniboard_{COLOR}',
  'name' => clienttranslate("MC"),
  'state' => 42,
],
 'tracker_ps' => [  //
  'type' => 'tracker',
  'create' => 4,
  'location' => 'miniboard_{COLOR}',
  'name' => clienttranslate("Steel Production"),
  'state' => 1,
],
 'tracker_s' => [  //
  'type' => 'tracker',
  'create' => 4,
  'location' => 'miniboard_{COLOR}',
  'name' => clienttranslate("Steel"),
  'state' => 0,
],
 'tracker_pu' => [  //
  'type' => 'tracker',
  'create' => 4,
  'location' => 'miniboard_{COLOR}',
  'name' => clienttranslate("Titanium Production"),
  'state' => 1,
],
 'tracker_u' => [  //
  'type' => 'tracker',
  'create' => 4,
  'location' => 'miniboard_{COLOR}',
  'name' => clienttranslate("Titanium"),
  'state' => 0,
],
 'tracker_pp' => [  //
  'type' => 'tracker',
  'create' => 4,
  'location' => 'miniboard_{COLOR}',
  'name' => clienttranslate("Plant Production"),
  'state' => 1,
],
 'tracker_p' => [  //
  'type' => 'tracker',
  'create' => 4,
  'location' => 'miniboard_{COLOR}',
  'name' => clienttranslate("Plant"),
  'state' => 0,
],
 'tracker_pe' => [  //
  'type' => 'tracker',
  'create' => 4,
  'location' => 'miniboard_{COLOR}',
  'name' => clienttranslate("Energy Production"),
  'state' => 1,
],
 'tracker_e' => [  //
  'type' => 'tracker',
  'create' => 4,
  'location' => 'miniboard_{COLOR}',
  'name' => clienttranslate("Energy"),
  'state' => 0,
],
 'tracker_ph' => [  //
  'type' => 'tracker',
  'create' => 4,
  'location' => 'miniboard_{COLOR}',
  'name' => clienttranslate("Heat Production"),
  'state' => 1,
],
 'tracker_h' => [  //
  'type' => 'tracker',
  'create' => 4,
  'location' => 'miniboard_{COLOR}',
  'name' => clienttranslate("Heat"),
  'state' => 0,
],
// #terraforming parameters
 'tracker_o' => [  //
  'type' => 'param',
  'create' => 1,
  'location' => 'params',
  'name' => clienttranslate("Oxigen Level"),
  'state' => 0,
  'max'=>14,
],
 'tracker_t' => [  //
  'type' => 'param',
  'create' => 1,
  'location' => 'params',
  'name' => clienttranslate("Temperature"),
  'state' => -30,
  'max'=>8,'min'=>-30,
],
 'tracker_w' => [  //
  'type' => 'param',
  'create' => 1,
  'location' => 'params',
  'name' => clienttranslate("Oceans"),
  'state' => 0,
  'max'=>9,
],
 'tracker_gen' => [  //
  'type' => 'param',
  'create' => 1,
  'location' => 'params',
  'name' => clienttranslate("Generations"),
  'state' => 0,
  'min'=>0,
],
// #tags
 'tagScience' => [  //
  'type' => 'tag',
  'create' => 0,
  'location' => 'params',
  'name' => clienttranslate("Science"),
],
 'tagBuilding' => [  //
  'type' => 'tag',
  'create' => 0,
  'location' => 'params',
  'name' => clienttranslate("Building"),
],
 'tagSpace' => [  //
  'type' => 'tag',
  'create' => 0,
  'location' => 'params',
  'name' => clienttranslate("Space"),
],
 'tagMicrobe' => [  //
  'type' => 'tag',
  'create' => 0,
  'location' => 'params',
  'name' => clienttranslate("Microbe"),
],
 'tagPlant' => [  //
  'type' => 'tag',
  'create' => 0,
  'location' => 'params',
  'name' => clienttranslate("Plant"),
],
 'tagAnimal' => [  //
  'type' => 'tag',
  'create' => 0,
  'location' => 'params',
  'name' => clienttranslate("Animal"),
],
 'tagCity' => [  //
  'type' => 'tag',
  'create' => 0,
  'location' => 'params',
  'name' => clienttranslate("City"),
],
 'tagEarth' => [  //
  'type' => 'tag',
  'create' => 0,
  'location' => 'params',
  'name' => clienttranslate("Earth"),
],
 'tagJovian' => [  //
  'type' => 'tag',
  'create' => 0,
  'location' => 'params',
  'name' => clienttranslate("Jovian"),
],
 'tagEnergy' => [  //
  'type' => 'tag',
  'create' => 0,
  'location' => 'params',
  'name' => clienttranslate("Energy"),
],
 'tagVenus' => [  //
  'type' => 'tag',
  'create' => 0,
  'location' => 'params',
  'name' => clienttranslate("Venus"),
],
 'tagEvent' => [  //
  'type' => 'tag',
  'create' => 0,
  'location' => 'params',
  'name' => clienttranslate("Event"),
],
// #hex tiles
 'tile_2' => [  //
  'type' => 'tile',
  'create' => 2,
  'location' => 'limbo',
  'count' => 20,
  'name' => clienttranslate("City"),
],
 'tile_1' => [  //
  'type' => 'tile',
  'create' => 2,
  'location' => 'limbo',
  'count' => 20,
  'name' => clienttranslate("Forest"),
],
 'tile_3' => [  //
  'type' => 'tile',
  'create' => 2,
  'location' => 'limbo',
  'count' => 9,
  'name' => clienttranslate("Ocean"),
],
/* --- gen php end tracker_material --- */
/* --- gen php begin map_material --- */
// #tharsis - can do variants later
// #r - placement bonus, p - plant, s - steal, u - titanium, draw - card
// #ocean - 1 if reserved for ocean
 'hex_1_1' => [  //
  'tooltip' => clienttranslate("hex at (1,1)"),
  'x' => 1,
  'y' => 1,
  'r' => '2p',
  'name' => clienttranslate("Noctus City"),
],
 'hex_1_2' => [  //
  'tooltip' => clienttranslate("hex at (1,2)"),
  'x' => 1,
  'y' => 2,
  'r' => '1p',
  'ocean' => 1,
],
 'hex_2_2' => [  //
  'tooltip' => clienttranslate("hex at (2,2)"),
  'x' => 2,
  'y' => 2,
  'r' => 'draw',
  'ocean' => 1,
],
/* --- gen php end map_material --- */
];



